/**
 * The Funnies — The Ninety-Nine (SA-090 / F-136).
 *
 * The flock of Luke 15:4, dryly commentating on being the responsible ones
 * nobody wrote a parable about. Captions live here, written against each
 * drawn panel; the panels themselves are generated by Codex from
 * scripts/imagery/strip-panel-subjects.json and installed to
 * public/images/edition/strip/.
 *
 * THE GENERATOR ONLY SERVES PANELS THAT EXIST ON DISK. Until the bank is
 * installed the section renders nothing (F-098's empty-section contract) —
 * no placeholder, and never the retired fedora panels. Rows land as
 * 'draft': caption + image together are editorial voice and pass the queue.
 */
import fs from 'node:fs'
import path from 'node:path'
import type { EditionItem } from '../kinds'

interface StripEntry {
  panelId: string
  /** Basename in public/images/edition/strip/. */
  file: string
  alt: string
  caption: string
}

/** Captions written against the drawn panels, one per panel id. */
export const STRIP_BANK: StripEntry[] = [
  {
    panelId: 'strip-001-headcount',
    file: 'strip-001-headcount.webp',
    alt: 'A fold full of sheep, one standing upright at the front as the rest graze; the gate stands open',
    caption: 'Ninety-eight, ninety-nine — and he counts US nightly.',
  },
  {
    panelId: 'strip-002-the-gap',
    file: 'strip-002-the-gap.webp',
    alt: 'The flock bunched at one end of the fold wall, one sheep alone midway, looking at the open gate',
    caption: 'Nobody is saying you can’t. Nobody has ever needed to.',
  },
  {
    panelId: 'strip-003-the-crook',
    file: 'strip-003-the-crook.webp',
    alt: 'A shepherd’s crook leaning against the fold wall beside the open gate, the flock watching it',
    caption: 'He left the staff. So this is fine. This is all fine.',
  },
  {
    panelId: 'strip-004-single-file',
    file: 'strip-004-single-file.webp',
    alt: 'Ninety-nine sheep in a perfectly even single-file line along a hill path; one distant sheep off the path',
    caption:
      'The line is not the point, the line has never been the point, stay in the line.',
  },
  {
    panelId: 'strip-005-the-ridge',
    file: 'strip-005-the-ridge.webp',
    alt: 'The flock asleep in the fold at night; one sheep awake at the wall watching a distant shepherd carry something home',
    caption: 'Wake the others? They said to be asleep. They were very clear.',
  },
  {
    panelId: 'strip-006-grass-audit',
    file: 'strip-006-grass-audit.webp',
    alt: 'Six sheep grazing one nearly bare patch while untouched pasture surrounds them',
    caption: 'The grass over there is unverified.',
  },
  {
    panelId: 'strip-007-the-return',
    file: 'strip-007-the-return.webp',
    alt: 'The shepherd setting the found sheep down at the gate before a rigid semicircle of ninety-nine',
    caption: 'We’re not angry. We stayed, and we’re not angry.',
  },
  {
    panelId: 'strip-008-one-missing-where',
    file: 'strip-008-one-missing-where.webp',
    alt: 'The flock from behind, every head turned toward one sheep-shaped gap in their own middle',
    caption: 'Has anyone checked the minutes from last night’s headcount?',
  },
  {
    panelId: 'strip-009-the-lamp',
    file: 'strip-009-the-lamp.webp',
    alt: 'A clay lamp burning in a niche above the open gate at night; one sheep awake beneath it',
    caption: 'It’s not for anyone. It’s just on.',
  },
  {
    panelId: 'strip-010-committee',
    file: 'strip-010-committee.webp',
    alt: 'Seven sheep in a tight ring in an empty pasture while the shepherd walks the far ridge away',
    caption:
      'Moving that the search was premature. Seconded. Carried, ninety-nine to nothing.',
  },
]

const STRIP_DIR = path.join(process.cwd(), 'public/images/edition/strip')

function dayOfYearUTC(date: Date): number {
  const startOfYear = Date.UTC(date.getUTCFullYear(), 0, 1)
  return (
    Math.floor(
      (Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) -
        startOfYear) /
        86400000,
    ) + 1
  )
}

export async function generateStrip(
  date: Date,
): Promise<EditionItem<'strip'>[]> {
  // Only panels whose artwork is actually installed. An empty pool is NOT an
  // error — the bank simply is not drawn yet, and the section stays absent.
  const available = STRIP_BANK.filter((e) =>
    fs.existsSync(path.join(STRIP_DIR, e.file)),
  )
  if (available.length === 0) return []

  const entry = available[dayOfYearUTC(date) % available.length]
  return [
    {
      kind: 'strip',
      publishDate: date.toISOString().slice(0, 10),
      slot: 0,
      status: 'draft',
      payload: {
        image: `/images/edition/strip/${entry.file}`,
        alt: entry.alt,
        caption: entry.caption,
        panelId: entry.panelId,
      },
    },
  ]
}
