#!/usr/bin/env tsx
/**
 * R35: cache substack header images locally so we serve them from
 * Cloudflare Workers Assets instead of hot-linking
 * substack-post-media.s3.amazonaws.com on every load.
 *
 * Reads src/data/substack-sources.ts, downloads each
 * substackImage URL into public/images/substack-cache/<hash>.<ext>,
 * and re-emits substack-sources.ts with substackImageLocal pointing
 * at the local path. Original substackImage URL is preserved so the
 * fallback still works if a build is run against a stale cache.
 *
 * Idempotent: re-running skips files that already exist on disk.
 */

import * as crypto from 'crypto'
import * as fs from 'fs'
import * as path from 'path'

const REPO = process.cwd()
const SOURCES_TS = path.join(REPO, 'src', 'data', 'substack-sources.ts')
const CACHE_DIR = path.join(REPO, 'public', 'images', 'substack-cache')

interface SubstackEntry {
  slug: string
  substackUrl: string
  substackImage: string | null
  substackImageLocal?: string | null
}

function hashUrl(url: string): string {
  return crypto.createHash('sha1').update(url).digest('hex').slice(0, 12)
}

function extFromUrl(url: string): string {
  const m = url.toLowerCase().match(/\.(png|jpe?g|webp|gif|avif)(\?.*)?$/)
  if (!m) return 'jpg'
  return m[1] === 'jpeg' ? 'jpg' : m[1]
}

async function downloadOne(url: string, dest: string): Promise<boolean> {
  try {
    const res = await fetch(url)
    if (!res.ok) {
      console.warn(`  SKIP (${res.status}): ${url}`)
      return false
    }
    const buf = Buffer.from(await res.arrayBuffer())
    fs.writeFileSync(dest, buf)
    return true
  } catch (e) {
    console.warn(`  FAIL: ${url} :: ${(e as Error).message}`)
    return false
  }
}

function parseSources(): SubstackEntry[] {
  const txt = fs.readFileSync(SOURCES_TS, 'utf-8')
  const out: SubstackEntry[] = []
  const re =
    /['"]([a-z][a-z0-9-]+)['"]:\s*\{\s*substackUrl:\s*['"]([^'"]+)['"]\s*,\s*substackImage:\s*(?:['"]([^'"]+)['"]|(null))/g
  let m: RegExpExecArray | null
  while ((m = re.exec(txt)) !== null) {
    out.push({
      slug: m[1],
      substackUrl: m[2],
      substackImage: m[3] ?? null,
    })
  }
  return out
}

function emitSources(entries: SubstackEntry[]) {
  const sorted = [...entries].sort((a, b) => a.slug.localeCompare(b.slug))
  const lines: string[] = []
  lines.push(
    `/**`,
    ` * Auto-generated by scripts/build-substack-sources.ts +`,
    ` * scripts/cache-substack-images.ts.`,
    ` *`,
    ` * Maps each substack-sourced devotional slug → its canonical`,
    ` * Substack post URL + the post's primary header image. We now`,
    ` * cache the image locally under public/images/substack-cache/`,
    ` * (R35) and prefer the local path; substackImage retains the`,
    ` * substack-post-media S3 URL as a fallback in case the local`,
    ` * file isn't deployed.`,
    ` *`,
    ` * Do NOT edit by hand.`,
    ` */`,
    ``,
    `export interface SubstackSource {`,
    `  substackUrl: string`,
    `  substackImage: string | null`,
    `  substackImageLocal: string | null`,
    `}`,
    ``,
    `export const SUBSTACK_SOURCES: Record<string, SubstackSource> = {`,
  )
  for (const e of sorted) {
    lines.push(`  ${JSON.stringify(e.slug)}: {`)
    lines.push(`    substackUrl: ${JSON.stringify(e.substackUrl)},`)
    lines.push(`    substackImage: ${e.substackImage ? JSON.stringify(e.substackImage) : 'null'},`)
    lines.push(`    substackImageLocal: ${e.substackImageLocal ? JSON.stringify(e.substackImageLocal) : 'null'},`)
    lines.push(`  },`)
  }
  lines.push(`}`, ``)
  fs.writeFileSync(SOURCES_TS, lines.join('\n'), 'utf-8')
}

async function main() {
  fs.mkdirSync(CACHE_DIR, { recursive: true })
  const entries = parseSources()
  console.log(`Loaded ${entries.length} substack entries.`)
  let cached = 0
  let skipped = 0
  let failed = 0
  for (const e of entries) {
    if (!e.substackImage) continue
    const hash = hashUrl(e.substackImage)
    const ext = extFromUrl(e.substackImage)
    const filename = `${hash}.${ext}`
    const dest = path.join(CACHE_DIR, filename)
    const localPath = `/images/substack-cache/${filename}`
    if (fs.existsSync(dest)) {
      e.substackImageLocal = localPath
      skipped += 1
      continue
    }
    const ok = await downloadOne(e.substackImage, dest)
    if (ok) {
      e.substackImageLocal = localPath
      cached += 1
    } else {
      e.substackImageLocal = null
      failed += 1
    }
  }
  console.log(`Cached new: ${cached}; already on disk: ${skipped}; failed: ${failed}`)
  emitSources(entries)
  console.log(`Wrote ${SOURCES_TS} with ${entries.length} entries.`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
