#!/usr/bin/env tsx
/**
 * R35 / R37: cache substack images locally so we serve them from
 * Cloudflare Workers Assets instead of hot-linking
 * substack-post-media.s3.amazonaws.com on every load.
 *
 * R37 extension: cache EVERY image in each substack post (not just
 * the header), and emit substackImagesLocal[] alongside the existing
 * substackImageLocal. SUBSTACK_SOURCES gains an `images` shape; the
 * DevotionalPageClient uses all of them in the rhythm rail.
 *
 * Idempotent: re-running skips files that already exist on disk.
 */

import * as crypto from 'crypto'
import * as fs from 'fs'
import * as path from 'path'

const REPO = process.cwd()
const SOURCES_TS = path.join(REPO, 'src', 'data', 'substack-sources.ts')
const CACHE_DIR = path.join(REPO, 'public', 'images', 'substack-cache')

interface SubstackEntry {
  slug: string
  substackUrl: string
  substackImage: string | null
  substackImages: string[]
  substackImageLocal?: string | null
  substackImagesLocal?: string[]
}

function hashUrl(url: string): string {
  return crypto.createHash('sha1').update(url).digest('hex').slice(0, 12)
}

function extFromUrl(url: string): string {
  const m = url.toLowerCase().match(/\.(png|jpe?g|webp|gif|avif)(\?.*)?$/)
  if (!m) return 'jpg'
  return m[1] === 'jpeg' ? 'jpg' : m[1]
}

async function downloadOne(url: string, dest: string): Promise<boolean> {
  try {
    const res = await fetch(url)
    if (!res.ok) {
      console.warn(`  SKIP (${res.status}): ${url}`)
      return false
    }
    const buf = Buffer.from(await res.arrayBuffer())
    fs.writeFileSync(dest, buf)
    return true
  } catch (e) {
    console.warn(`  FAIL: ${url} :: ${(e as Error).message}`)
    return false
  }
}

function parseSources(): SubstackEntry[] {
  const txt = fs.readFileSync(SOURCES_TS, 'utf-8')
  const out: SubstackEntry[] = []
  // Match per-slug blocks; pull out substackUrl, substackImage,
  // substackImages (the array). The blocks are well-formed
  // multi-line. We look for the closing `},` boundary.
  const blockRe = /['"]([a-z][a-z0-9-]+)['"]:\s*\{([\s\S]*?)\n\s*\},/g
  let b: RegExpExecArray | null
  while ((b = blockRe.exec(txt)) !== null) {
    const slug = b[1]
    const body = b[2]
    const urlMatch = body.match(/substackUrl:\s*['"]([^'"]+)['"]/)
    const imgMatch = body.match(/substackImage:\s*['"]([^'"]+)['"]/)
    const imagesMatch = body.match(/substackImages:\s*\[([\s\S]*?)\]/)
    const images: string[] = []
    if (imagesMatch) {
      const inner = imagesMatch[1]
      const imRe = /['"]([^'"]+)['"]/g
      let m: RegExpExecArray | null
      while ((m = imRe.exec(inner)) !== null) images.push(m[1])
    }
    if (!urlMatch) continue
    out.push({
      slug,
      substackUrl: urlMatch[1],
      substackImage: imgMatch ? imgMatch[1] : null,
      substackImages: images.length > 0 ? images : imgMatch ? [imgMatch[1]] : [],
    })
  }
  return out
}

function emitSources(entries: SubstackEntry[]) {
  const sorted = [...entries].sort((a, b) => a.slug.localeCompare(b.slug))
  const lines: string[] = []
  lines.push(
    `/**`,
    ` * Auto-generated by scripts/build-substack-sources.ts +`,
    ` * scripts/cache-substack-images.ts.`,
    ` *`,
    ` * Maps each substack-sourced devotional slug → its canonical`,
    ` * Substack post URL + every image in the post (R37). Each image`,
    ` * is cached locally under public/images/substack-cache/ so LCP`,
    ` * isn't tied to substack's edge.`,
    ` *`,
    ` * Do NOT edit by hand. Re-run`,
    ` * scripts/build-substack-sources.ts then`,
    ` * scripts/cache-substack-images.ts to refresh.`,
    ` */`,
    ``,
    `export interface SubstackSource {`,
    `  substackUrl: string`,
    `  substackImage: string | null`,
    `  substackImages: string[]`,
    `  substackImageLocal: string | null`,
    `  substackImagesLocal: string[]`,
    `}`,
    ``,
    `export const SUBSTACK_SOURCES: Record<string, SubstackSource> = {`,
  )
  for (const e of sorted) {
    lines.push(`  ${JSON.stringify(e.slug)}: {`)
    lines.push(`    substackUrl: ${JSON.stringify(e.substackUrl)},`)
    lines.push(
      `    substackImage: ${e.substackImage ? JSON.stringify(e.substackImage) : 'null'},`,
    )
    lines.push(`    substackImages: ${JSON.stringify(e.substackImages)},`)
    lines.push(
      `    substackImageLocal: ${e.substackImageLocal ? JSON.stringify(e.substackImageLocal) : 'null'},`,
    )
    lines.push(
      `    substackImagesLocal: ${JSON.stringify(e.substackImagesLocal ?? [])},`,
    )
    lines.push(`  },`)
  }
  lines.push(`}`, ``)
  fs.writeFileSync(SOURCES_TS, lines.join('\n'), 'utf-8')
}

async function cacheImage(url: string): Promise<string | null> {
  const hash = hashUrl(url)
  const ext = extFromUrl(url)
  const filename = `${hash}.${ext}`
  const dest = path.join(CACHE_DIR, filename)
  const localPath = `/images/substack-cache/${filename}`
  if (fs.existsSync(dest)) return localPath
  const ok = await downloadOne(url, dest)
  return ok ? localPath : null
}

async function main() {
  fs.mkdirSync(CACHE_DIR, { recursive: true })
  const entries = parseSources()
  console.log(`Loaded ${entries.length} substack entries.`)
  let totalImages = 0
  let cached = 0
  let alreadyOnDisk = 0
  let failed = 0
  for (const e of entries) {
    const all = e.substackImages?.length ? e.substackImages : e.substackImage ? [e.substackImage] : []
    const local: string[] = []
    for (const url of all) {
      totalImages += 1
      const hash = hashUrl(url)
      const ext = extFromUrl(url)
      const filename = `${hash}.${ext}`
      const dest = path.join(CACHE_DIR, filename)
      if (fs.existsSync(dest)) {
        local.push(`/images/substack-cache/${filename}`)
        alreadyOnDisk += 1
      } else {
        const p = await cacheImage(url)
        if (p) {
          local.push(p)
          cached += 1
        } else {
          local.push('')
          failed += 1
        }
      }
    }
    e.substackImagesLocal = local
    e.substackImageLocal = local[0] || null
  }
  console.log(
    `Total images: ${totalImages}; newly cached: ${cached}; already on disk: ${alreadyOnDisk}; failed: ${failed}.`,
  )
  emitSources(entries)
  console.log(`Wrote ${SOURCES_TS}.`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
