import { SERIES_DATA, NEW_SERIES_ORDER } from '@/data/series'
import { DEVOTIONAL_PUBLISH_DATES } from '@/data/devotional-publish-dates'

/**
 * The homepage's featured slot, DERIVED rather than declared (SA-136).
 *
 * SA-031 already ruled that the main feature belongs to the most recent
 * series. It was implemented as a hand-edited object in `src/app/page.tsx`,
 * and it drifted exactly as you would expect: Sought and Crowned shipped on
 * 2026-09-05 and the homepage went on featuring Drawing Near, because
 * publishing a series and editing the constant are two separate acts and only
 * one of them is enforced.
 *
 * Founder, 2026-09-08: "the featured devotional should be the latest
 * devotional added to the site. That should be a standing rule."
 *
 * A rule that depends on somebody remembering is not a rule, so this computes
 * it. The featured series is now whichever series has the newest publication
 * date, and shipping a series IS updating the homepage.
 *
 * WHY PUBLISH DATES AND NOT THE ORDER ARRAY: `NEW_SERIES_ORDER` is
 * append-only by convention, not by enforcement, and a series inserted in the
 * middle would silently take the slot. `devotional-publish-dates.ts` is
 * generated from `git log --diff-filter=A` — the day a devotional actually
 * entered the repo — so it cannot be wrong about which came last, and it is
 * regenerated by a pre-commit gate that fails when a devotional has no date.
 *
 * `first-seen` dates are excluded: they record the day a bulk-import script
 * ran, not a publication, and the file's own header says so. Letting one of
 * those win would hand the homepage to whichever legacy file a migration
 * happened to touch most recently.
 */

/** Series whose date rests on a real publishing event, newest first. */
function seriesByRecency(): string[] {
  const newest = new Map<string, string>()

  for (const [daySlug, record] of Object.entries(DEVOTIONAL_PUBLISH_DATES)) {
    if (record.source === 'first-seen') continue
    const series = NEW_SERIES_ORDER.find((slug) =>
      daySlug.startsWith(`${slug}-day-`),
    )
    if (!series) continue
    const current = newest.get(series)
    if (!current || record.publishedAt > current) {
      newest.set(series, record.publishedAt)
    }
  }

  return [...newest.entries()]
    .sort((a, b) => (a[1] < b[1] ? 1 : a[1] > b[1] ? -1 : 0))
    .map(([series]) => series)
}

export interface FeaturedSeries {
  series: string
  daySlug: string
  dayTitle: string
  kicker: string
  title: string
  scripture: string
  teaser: string
  featuredArt: string
}

/**
 * The most recently published series, shaped for the homepage feature.
 *
 * Falls back to the last entry in NEW_SERIES_ORDER if no dated series
 * resolves — which would mean the publish-date register is empty, a state the
 * pre-commit gate already refuses to allow.
 */
export function latestFeaturedSeries(): FeaturedSeries {
  const ranked = seriesByRecency()
  const slug =
    ranked.find((s) => SERIES_DATA[s]) ??
    [...NEW_SERIES_ORDER].reverse().find((s) => SERIES_DATA[s]) ??
    'drawing-near'

  const info = SERIES_DATA[slug]
  const firstDay = info.days[0]

  // The kicker states the shape of the offer, not a slogan: what it is, how
  // long it takes, and where it is anchored. The anchor is the first clause of
  // the framework, which is where the reference lives.
  const anchor = info.framework.split(/\s+[-–—]\s+/)[0].trim()

  return {
    series: slug,
    daySlug: firstDay.slug,
    dayTitle: firstDay.title,
    kicker: `FEATURED SERIES · ${info.days.length} DAYS · ${anchor.toUpperCase()}`,
    title: info.title,
    scripture: anchor,
    // Founder 2026-08-16: "the text on the right should not have soo much —
    // 10-14 words max." The series QUESTION is the line the reader carries;
    // the full introduction is one tap away on the series page.
    teaser: info.question,
    featuredArt: info.heroImage ?? `/images/site/series/${slug}.webp`,
  }
}
