-- Add 'ai_generative' to the audit_selections.option_kind CHECK constraint.
-- This value is used for generative devotional plans where Days 2-7 are
-- progressively generated by LLM (as opposed to 'ai_primary' which generates
-- all days at selection time).

-- Single ALTER TABLE statement: atomic even without explicit transaction.
-- Note: The constraint name is PostgreSQL's default for inline CHECK on the
-- original CREATE TABLE. Verify with:
--   SELECT conname FROM pg_constraint
--   WHERE conrelid = 'audit_selections'::regclass AND contype = 'c';
ALTER TABLE audit_selections
  DROP CONSTRAINT IF EXISTS audit_selections_option_kind_check,
  ADD CONSTRAINT audit_selections_option_kind_check
  CHECK (option_kind IN ('ai_primary', 'ai_generative', 'curated_prefab'));
