/**
 * The Voices bank — real attributed quotes, deterministically rotated.
 *
 * The bank is generated by scripts/edition/build-voices-bank.mjs from the
 * committed reference index, with attribution verified against the actual
 * source files (the corpus contains mislabeled Gutenberg bundles, so the
 * path alone is never trusted). These tests hold the contract: an honest
 * floor of entries, every quote substantial and attributed to a real
 * person + work, and a selection that is pure UTC-day arithmetic — same
 * day, same voice, no repeats inside a 30-day window.
 */
import { describe, expect, it } from 'vitest'
import { VOICES, pickVoiceForDay } from '@/data/voices-bank'

const wordCount = (s: string) => s.split(/\s+/).filter(Boolean).length

const utcDay = (y: number, m: number, d: number) =>
  new Date(Date.UTC(y, m, d))

describe('voices bank contents', () => {
  it('respects the honest floor and the cap', () => {
    // The build reached the full cap honestly (200 verified entries).
    expect(VOICES.length).toBeGreaterThanOrEqual(100)
    expect(VOICES.length).toBeLessThanOrEqual(200)
  })

  it('every entry has a non-empty quote, author, and work', () => {
    for (const entry of VOICES) {
      expect(entry.quote.trim().length).toBeGreaterThan(0)
      expect(entry.author.trim().length).toBeGreaterThan(0)
      expect(entry.work.trim().length).toBeGreaterThan(0)
    }
  })

  it('no quote is shorter than 25 words or longer than 110', () => {
    for (const entry of VOICES) {
      const wc = wordCount(entry.quote)
      expect(wc).toBeGreaterThanOrEqual(25)
      expect(wc).toBeLessThanOrEqual(110)
    }
  })

  it('no author field looks editorial', () => {
    const editorial = /\b(editor|editors|editorial|unknown|anonymous)\b/i
    for (const entry of VOICES) {
      expect(entry.author).not.toMatch(editorial)
    }
  })
})

describe('pickVoiceForDay', () => {
  it('is deterministic across the whole UTC day', () => {
    const midnight = new Date(Date.UTC(2026, 7, 19, 0, 0, 0))
    const noon = new Date(Date.UTC(2026, 7, 19, 12, 30, 45))
    const lastSecond = new Date(Date.UTC(2026, 7, 19, 23, 59, 59))
    const picked = pickVoiceForDay(midnight)
    expect(pickVoiceForDay(noon)).toBe(picked)
    expect(pickVoiceForDay(lastSecond)).toBe(picked)
  })

  it('is days-since-epoch arithmetic, not anything cleverer', () => {
    const date = utcDay(2026, 7, 19)
    const daysSinceEpoch = Math.floor(date.getTime() / 86_400_000)
    expect(pickVoiceForDay(date)).toBe(
      VOICES[daysSinceEpoch % VOICES.length],
    )
  })

  it('advances by exactly one voice per day', () => {
    const today = pickVoiceForDay(utcDay(2026, 0, 10))
    const index = VOICES.indexOf(today)
    expect(pickVoiceForDay(utcDay(2026, 0, 11))).toBe(
      VOICES[(index + 1) % VOICES.length],
    )
  })

  it('never repeats a voice inside any 30-day window', () => {
    // Cross a month AND a year boundary to catch calendar arithmetic slips.
    const starts = [utcDay(2026, 7, 1), utcDay(2026, 11, 20)]
    for (const start of starts) {
      const seen = new Set<string>()
      for (let offset = 0; offset < 30; offset += 1) {
        const day = new Date(start.getTime() + offset * 86_400_000)
        const entry = pickVoiceForDay(day)
        seen.add(`${entry.author}::${entry.quote}`)
      }
      expect(seen.size).toBe(30)
    }
  })
})
