// Auto-generated by scripts/generate-artwork-manifest.mjs
// Do not edit manually. Run: npm run generate:artwork-manifest

export interface ArtworkEntry {
  slug: string
  title: string
  artist: string
  year: string
  medium: string
  museum: string
  license: string
  printStyle: string
  src: string
  rawSrc: string
  relevance: string
}

export const SERIES_HERO: Record<string, ArtworkEntry> = {
}

export const DEVOTIONAL_ARTWORKS: Record<string, ArtworkEntry[]> = {
}

export const ALL_ARTWORKS: Record<string, ArtworkEntry> = {
}
