// AUTO-GENERATED by scripts/generate-devotional-teasers.mjs
// Do not edit by hand. Re-run via `npm run build` (or the script directly).

export const DEVOTIONAL_TEASERS: Record<string, string> = {
  'abiding-in-his-presence-day-1':
    'Moving beyond spiritual visits to spiritual residence with God',
  'abiding-in-his-presence-day-2':
    "Discovering God's hidden refuge where we can be completely authentic and safe",
  'abiding-in-his-presence-day-3':
    'Understanding that God has permanently relocated to dwell with us',
  'abiding-in-his-presence-day-4':
    'Understanding that spiritual fruit is borne through connection, not produced through effort',
  'abiding-in-his-presence-day-5':
    "Maintaining connection to Jesus when life's pressures threaten to overwhelm",
  'abiding-in-his-presence-day-6':
    'Integrating continuous communion with God into every aspect of daily life',
  'anointed-day-1': "Your anointing isn't about position — it's about calling",
  'anointed-day-2':
    'The Holy Spirit empowers you for witness — not just words, but presence',
  'anointed-day-3':
    'Your hidden seasons are not wasted — they are the training ground for greatness',
  'anointed-day-4':
    "God's anointing is oil for wounds — His presence heals what is broken",
  'anointed-day-5': "Anointing is not to keep — it's to give. You are sent.",
  'bible-365-day-1':
    'A year-long walk through Scripture begins with four words that change everything: in the beginning, God.',
  'bible-365-day-10':
    'Day 10 of Bible 365 - Genesis 8:20-9:17. A pleasing aroma rises, and God hangs His war-bow in the clouds, aimed away.',
  'bible-365-day-100':
    'Solomon never renounced the LORD. He simply stopped being all-in. The drift that loses a kingdom begins with a heart divided, not denied.',
  'bible-365-day-101':
    "Solomon's heart did not turn in a day. It leaned, then loved, then followed. And still God keeps a lamp burning for David's house.",
  'bible-365-day-102':
    "Solomon didn't fall in a day. His heart was carried off one small loyalty at a time — and the wisest man alive never felt the floor tilt.",
  'bible-365-day-103':
    'The wisest king in the world was not undone by a single great sin but by a thousand small affections, until his heart was no longer whole. The kingdom tore where the heart divided.',
  'bible-365-day-104':
    'The wisest king alive did not lose his throne to an army. He lost his heart one foreign altar at a time — and still God kept a lamp burning for David.',
  'bible-365-day-105':
    "Solomon doesn't fall in a day. His heart is inclined, degree by degree, by what he loved most — and the kingdom is kept only for the sake of a greater Son.",
  'bible-365-day-106':
    "One harsh word splits a kingdom in a single afternoon. But the same God who tears it keeps a lamp burning in David's house — for the sake of the Son who would gather the torn flock back into one.",
  'bible-365-day-107':
    'Ten tribes walk away over one harsh word, golden calves go up at Bethel and Dan — and into the wreckage God speaks a name three hundred years early.',
  'bible-365-day-108':
    'The kingdom splits in two not over taxes but over worship. Jeroboam builds altars close to home so no one has to go up to Jerusalem — and a nation learns to worship what costs it nothing.',
  'bible-365-day-109':
    'Jeroboam decides the trip to Jerusalem costs too much, so he builds a calf you can reach without leaving home. The application is uncomfortably close: the gods we make to keep control.',
  'bible-365-day-11':
    'On a plain in Shinar, humanity stacks bricks toward heaven to make a name for itself. God comes down, confuses the tongues, and scatters the builders. The name they grasped for is the one God later gives away for free.',
  'bible-365-day-110': 'Day 110 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-111':
    'Day 111 of Bible 365 — 1 Kings 12-16. A king splits a nation over a rough answer, and a frightened rival builds gods to keep his throne. Yet a lamp keeps burning for David.',
  'bible-365-day-112': 'Day 112 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-113':
    'Elijah called fire down on Carmel — then fell apart under a broom tree. God came to him next not in wind, quake, or fire, but in a whisper. The prophet of fire had to learn the voice of the still, small word.',
  'bible-365-day-114':
    'Elijah called down fire and won—then ran for his life and begged to die. At Horeb God was not in the wind, the quake, or the fire. He came in a whisper, and renamed the loneliness Elijah was certain of.',
  'bible-365-day-115':
    'Elijah called down fire on a mountain and then begged to die under a bush. At Horeb God is not in the wind or the quake or the fire — He is in the low, quiet voice.',
  'bible-365-day-116':
    'Elijah won on Carmel and then begged to die under a bush. God did not rebuke the burned-out prophet — He fed him, let him sleep, and came in a whisper.',
  'bible-365-day-117':
    "Elijah does not die. A whirlwind takes him, and the cloak drops at Elisha's feet. The cycle ends not with a grave but with a gift passed on.",
  'bible-365-day-118':
    'The prophet who called down fire from heaven begs to die in the desert. Then God passes by — not in wind, earthquake, or flame, but in a whisper.',
  'bible-365-day-119':
    'The day after fire fell from heaven, the prophet begged to die. God answered with bread, sleep, and a whisper.',
  'bible-365-day-12':
    'Eleven chapters in, the human story keeps reaching for heaven and coming apart. Babel is where the reaching finally breaks into noise - and where the canon starts leaning toward the One who will come down to gather what was scattered.',
  'bible-365-day-120':
    'A widow has nothing left but one jar of oil and a creditor at the door. Elisha tells her to borrow empty jars from the whole street. The oil keeps flowing until the jars run out — never the oil.',
  'bible-365-day-121':
    'A great man wanted a great cure. God offered him a river and seven small dips. The healing was free; only his pride had a price.',
  'bible-365-day-122':
    'A general carries silver and gold to buy a cure, and is told to dip in a muddy river seven times like a child. The gift he cannot purchase, he can only receive.',
  'bible-365-day-123':
    'The widow has nothing but a little oil and a houseful of borrowed vessels. Elisha tells her to keep pouring. The miracle stops only when the empty jars run out.',
  'bible-365-day-124':
    'Elisha spends his whole ministry handing life back to the dying — and then dies. But the last word is not the funeral. It is a corpse thrown into his tomb that touches his bones and stands up.',
  'bible-365-day-125':
    "Elisha's miracles are small and unglamorous - a borrowed jar, a river, twenty loaves. The grace runs through ordinary water, and it reaches the foreigner first.",
  'bible-365-day-126':
    "Across ten chapters of Elisha's life, the smallest acts carry God. A widow's jars. A river. A dead man's bones. On the Sabbath, sit with how God heals.",
  'bible-365-day-127':
    'Three farmers and shepherds shout the same thing at a nation drowning in worship: God never wanted the rams. He wanted you.',
  'bible-365-day-128':
    'Smoke climbs, choirs sing, and God says it makes Him sick. Amos, Hosea, and Micah indict a worship that floats on top of injustice - and point to the river that never runs dry.',
  'bible-365-day-129':
    'Three voices, one verdict: God never wanted your sacrifices. He wanted you — just, merciful, walking close. The prophets ask the impossible. Christ became the answer.',
  'bible-365-day-13':
    "God's first word to Abram is a command to leave everything for a land He won't name. The whole gospel is hidden in that one word: Go.",
  'bible-365-day-130':
    'Amos, Hosea, and Micah strip religion down to three things God actually requires — and then God comes in person to do all three.',
  'bible-365-day-131':
    'Three angry prophets reach the same verdict — and then each one breaks. The God who hates their worship cannot give them up.',
  'bible-365-day-132':
    'Amos thunders for justice; Hosea pleads for mercy. Both speak for the same God — and Hosea 11 shows us the war between them happening inside His own heart.',
  'bible-365-day-133':
    'Three prophets, one verdict: God never wanted your sacrifices. He wanted you to be like Him. Jesus made that line His mission statement.',
  'bible-365-day-134':
    'Assyria has swallowed every nation it touched. Then one king of Judah does the only thing the empire cannot answer: he carries the threat into the house of God and spreads it open before the LORD.',
  'bible-365-day-135':
    'A young king tears down the holy places — and smashes the bronze serpent that once healed Israel. The cure had curdled into an idol. So he breaks it, and trusts the LORD instead.',
  'bible-365-day-136': 'Day 136 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-137': 'Day 137 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-138': 'Day 138 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-139': 'Day 139 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-14':
    'The call to Abram begins with a leaving. Before the land, the name, the blessing, there is a door to walk out of - and a Voice worth trusting on the other side.',
  'bible-365-day-140': 'Day 140 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-141': 'Day 141 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-142': 'Day 142 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-143': 'Day 143 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-144': 'Day 144 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-145': 'Day 145 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-146': 'Day 146 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-147': 'Day 147 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-148': 'Day 148 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-149': 'Day 149 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-15': 'Day 15 of Bible 365 — Genesis 15:1-6',
  'bible-365-day-150': 'Day 150 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-151': 'Day 151 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-152': 'Day 152 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-153': 'Day 153 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-154': 'Day 154 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-155': 'Day 155 of Bible 365 — Lamentations',
  'bible-365-day-156': 'Day 156 of Bible 365 — Lamentations',
  'bible-365-day-157': 'Day 157 of Bible 365 — Lamentations',
  'bible-365-day-158': 'Day 158 of Bible 365 — Lamentations',
  'bible-365-day-159': 'Day 159 of Bible 365 — Lamentations',
  'bible-365-day-16':
    'Day 16 of Bible 365 — Genesis 17:1-8. At ninety-nine, with no son and no land, Abram hears a name for God big enough to carry an impossible promise.',
  'bible-365-day-160': 'Day 160 of Bible 365 — Lamentations',
  'bible-365-day-161': 'Day 161 of Bible 365 — Lamentations',
  'bible-365-day-162': 'Day 162 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-163': 'Day 163 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-164': 'Day 164 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-165': 'Day 165 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-166': 'Day 166 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-167': 'Day 167 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-168': 'Day 168 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-169': 'Day 169 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-17':
    'Three strangers stand at the door in the heat of the day. Abraham runs to feed them, and the meal turns out to be God Himself, come to keep an impossible promise.',
  'bible-365-day-170': 'Day 170 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-171': 'Day 171 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-172': 'Day 172 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-173': 'Day 173 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-174': 'Day 174 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-175': 'Day 175 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-176': 'Day 176 of Bible 365 — Esther 4-7',
  'bible-365-day-177': 'Day 177 of Bible 365 — Esther 4-7',
  'bible-365-day-178': 'Day 178 of Bible 365 — Esther 4-7',
  'bible-365-day-179': 'Day 179 of Bible 365 — Esther 4-7',
  'bible-365-day-18':
    'Day 18 of Bible 365 — Abraham steps toward the God who is leaving, and dares to argue for a city that deserves to burn. The first great intercession in Scripture rests on one conviction: the Judge of all the earth will do right.',
  'bible-365-day-180': 'Day 180 of Bible 365 — Esther 4-7',
  'bible-365-day-181': 'Day 181 of Bible 365 — Esther 4-7',
  'bible-365-day-182': 'Day 182 of Bible 365 — Esther 4-7',
  'bible-365-day-183': 'Day 183 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-184': 'Day 184 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-185': 'Day 185 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-186': 'Day 186 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-187': 'Day 187 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-188': 'Day 188 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-189': 'Day 189 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-19':
    'Day 19 of Bible 365 — Genesis 22:1-14. A father climbs Moriah to give up his only son, and learns that the lamb was never his to find. God provides it.',
  'bible-365-day-190':
    'Day 190 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-191':
    'Day 191 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-192':
    'Day 192 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-193':
    'Day 193 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-194':
    'Day 194 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-195':
    'Day 195 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-196':
    'Day 196 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-197': 'Day 197 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-198': 'Day 198 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-199': 'Day 199 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-2':
    'You did not earn your dignity. You were given it on the sixth day, before you ever did a thing.',
  'bible-365-day-20':
    'Day 20 of Bible 365 — Genesis 22 (deeper). Abraham says "Here I am" three times and walks his son up the mountain. What faith costs, and what God provides.',
  'bible-365-day-200': 'Day 200 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-201': 'Day 201 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-202': 'Day 202 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-203': 'Day 203 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-204': 'Day 204 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-205': 'Day 205 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-206': 'Day 206 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-207': 'Day 207 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-208': 'Day 208 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-209': 'Day 209 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-21': 'Day 21 of Bible 365 — Genesis 22 (sabbath)',
  'bible-365-day-210': 'Day 210 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-211': 'Day 211 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-212': 'Day 212 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-213': 'Day 213 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-214': 'Day 214 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-215': 'Day 215 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-216': 'Day 216 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-217': 'Day 217 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-218': 'Day 218 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-219': 'Day 219 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-22':
    'Esau came in from the field famished and sold his whole inheritance for one bowl of red stew. The hunger of the moment ate the promise of his life.',
  'bible-365-day-220': 'Day 220 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-221': 'Day 221 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-222': 'Day 222 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-223': 'Day 223 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-224': 'Day 224 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-225': 'Day 225 of Bible 365 — Isaiah 40-55',
  'bible-365-day-226': 'Day 226 of Bible 365 — Isaiah 40-55',
  'bible-365-day-227': 'Day 227 of Bible 365 — Isaiah 40-55',
  'bible-365-day-228': 'Day 228 of Bible 365 — Isaiah 40-55',
  'bible-365-day-229': 'Day 229 of Bible 365 — Isaiah 40-55',
  'bible-365-day-23':
    'A liar runs into the dark with a stone for a pillow, and heaven opens over his head. God meets Jacob before Jacob ever asks.',
  'bible-365-day-230': 'Day 230 of Bible 365 — Isaiah 40-55',
  'bible-365-day-231': 'Day 231 of Bible 365 — Isaiah 40-55',
  'bible-365-day-232': 'Day 232 of Bible 365 — Jeremiah 31',
  'bible-365-day-233': 'Day 233 of Bible 365 — Jeremiah 31',
  'bible-365-day-234': 'Day 234 of Bible 365 — Jeremiah 31',
  'bible-365-day-235': 'Day 235 of Bible 365 — Jeremiah 31',
  'bible-365-day-236': 'Day 236 of Bible 365 — Jeremiah 31',
  'bible-365-day-237': 'Day 237 of Bible 365 — Jeremiah 31',
  'bible-365-day-238': 'Day 238 of Bible 365 — Jeremiah 31',
  'bible-365-day-239': 'Day 239 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-24':
    'Day 24 of Bible 365 — Jacob the heel-grabber wrestles a stranger till dawn at the Jabbok, refuses to let go without a blessing, and walks away with a new name and a wound he will carry the rest of his life.',
  'bible-365-day-240': 'Day 240 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-241': 'Day 241 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-242': 'Day 242 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-243': 'Day 243 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-244': 'Day 244 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-245': 'Day 245 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-246': 'Day 246 of Bible 365 — Daniel 7, 9',
  'bible-365-day-247': 'Day 247 of Bible 365 — Daniel 7, 9',
  'bible-365-day-248': 'Day 248 of Bible 365 — Daniel 7, 9',
  'bible-365-day-249': 'Day 249 of Bible 365 — Daniel 7, 9',
  'bible-365-day-25':
    'Day 25 of Bible 365 — Genesis 33:1-11. The brother who swore to kill him runs, embraces him, and weeps. In a reconciled face, Jacob sees the face of God.',
  'bible-365-day-250': 'Day 250 of Bible 365 — Daniel 7, 9',
  'bible-365-day-251': 'Day 251 of Bible 365 — Daniel 7, 9',
  'bible-365-day-252': 'Day 252 of Bible 365 — Daniel 7, 9',
  'bible-365-day-253': 'Day 253 of Bible 365 — Selected',
  'bible-365-day-254': 'Day 254 of Bible 365 — Selected',
  'bible-365-day-255': 'Day 255 of Bible 365 — Selected',
  'bible-365-day-256': 'Day 256 of Bible 365 — Selected',
  'bible-365-day-257': 'Day 257 of Bible 365 — Selected',
  'bible-365-day-258': 'Day 258 of Bible 365 — Selected',
  'bible-365-day-259': 'Day 259 of Bible 365 — Selected',
  'bible-365-day-26':
    'Day 26 of Bible 365 — Genesis 35:1-15. God calls Jacob back to the place of his first promise. But first the foreign gods go into the ground, and the man who left as a fugitive comes home with a new name.',
  'bible-365-day-260': 'Day 260 of Bible 365 — Jonah 1-4',
  'bible-365-day-261': 'Day 261 of Bible 365 — Jonah 1-4',
  'bible-365-day-262': 'Day 262 of Bible 365 — Jonah 1-4',
  'bible-365-day-263': 'Day 263 of Bible 365 — Jonah 1-4',
  'bible-365-day-264': 'Day 264 of Bible 365 — Jonah 1-4',
  'bible-365-day-265': 'Day 265 of Bible 365 — Jonah 1-4',
  'bible-365-day-266': 'Day 266 of Bible 365 — Jonah 1-4',
  'bible-365-day-267': 'Day 267 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-268': 'Day 268 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-269': 'Day 269 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-27':
    'Jacob wrestles God in the dark and walks away wounded, renamed, and blessed. The hand that struck his hip is the hand that held him all night.',
  'bible-365-day-270': 'Day 270 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-271': 'Day 271 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-272': 'Day 272 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-273': 'Day 273 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-274': 'Day 274 of Bible 365 — Matthew 1-7',
  'bible-365-day-275': 'Day 275 of Bible 365 — Matthew 1-7',
  'bible-365-day-276': 'Day 276 of Bible 365 — Matthew 1-7',
  'bible-365-day-277': 'Day 277 of Bible 365 — Matthew 1-7',
  'bible-365-day-278': 'Day 278 of Bible 365 — Matthew 1-7',
  'bible-365-day-279': 'Day 279 of Bible 365 — Matthew 1-7',
  'bible-365-day-28':
    'Day 28 of Bible 365 — Sabbath. Jacob holds on until daybreak and walks away renamed and limping. Today you stop wrestling, because the blessing is already yours.',
  'bible-365-day-280': 'Day 280 of Bible 365 — Matthew 1-7',
  'bible-365-day-281': 'Day 281 of Bible 365 — Matthew 8-13',
  'bible-365-day-282': 'Day 282 of Bible 365 — Matthew 8-13',
  'bible-365-day-283': 'Day 283 of Bible 365 — Matthew 8-13',
  'bible-365-day-284': 'Day 284 of Bible 365 — Matthew 8-13',
  'bible-365-day-285': 'Day 285 of Bible 365 — Matthew 8-13',
  'bible-365-day-286': 'Day 286 of Bible 365 — Matthew 8-13',
  'bible-365-day-287': 'Day 287 of Bible 365 — Matthew 8-13',
  'bible-365-day-288': 'Day 288 of Bible 365 — Mark 1-16',
  'bible-365-day-289': 'Day 289 of Bible 365 — Mark 1-16',
  'bible-365-day-29': 'Day 29 of Bible 365 — Genesis 37',
  'bible-365-day-290': 'Day 290 of Bible 365 — Mark 1-16',
  'bible-365-day-291': 'Day 291 of Bible 365 — Mark 1-16',
  'bible-365-day-292': 'Day 292 of Bible 365 — Mark 1-16',
  'bible-365-day-293': 'Day 293 of Bible 365 — Mark 1-16',
  'bible-365-day-294': 'Day 294 of Bible 365 — Mark 1-16',
  'bible-365-day-295': 'Day 295 of Bible 365 — Luke 1-12',
  'bible-365-day-296': 'Day 296 of Bible 365 — Luke 1-12',
  'bible-365-day-297': 'Day 297 of Bible 365 — Luke 1-12',
  'bible-365-day-298': 'Day 298 of Bible 365 — Luke 1-12',
  'bible-365-day-299': 'Day 299 of Bible 365 — Luke 1-12',
  'bible-365-day-3':
    'God finishes a universe and the next thing He does is stop. Before any human ever earned a paycheck, rest was already built into the shape of the week.',
  'bible-365-day-30':
    "Four times in one chapter, the same sentence: the LORD was with him. It is written over Joseph's success and over his prison cell without changing a single word.",
  'bible-365-day-300': 'Day 300 of Bible 365 — Luke 1-12',
  'bible-365-day-301': 'Day 301 of Bible 365 — Luke 1-12',
  'bible-365-day-302': 'Day 302 of Bible 365 — Luke 15, 24',
  'bible-365-day-303': 'Day 303 of Bible 365 — Luke 15, 24',
  'bible-365-day-304': 'Day 304 of Bible 365 — Luke 15, 24',
  'bible-365-day-305': 'Day 305 of Bible 365 — Luke 15, 24',
  'bible-365-day-306': 'Day 306 of Bible 365 — Luke 15, 24',
  'bible-365-day-307': 'Day 307 of Bible 365 — Luke 15, 24',
  'bible-365-day-308': 'Day 308 of Bible 365 — Luke 15, 24',
  'bible-365-day-309': 'Day 309 of Bible 365 — John 1-7',
  'bible-365-day-31': 'Day 31 of Bible 365 — Genesis 41',
  'bible-365-day-310': 'Day 310 of Bible 365 — John 1-7',
  'bible-365-day-311': 'Day 311 of Bible 365 — John 1-7',
  'bible-365-day-312': 'Day 312 of Bible 365 — John 1-7',
  'bible-365-day-313': 'Day 313 of Bible 365 — John 1-7',
  'bible-365-day-314': 'Day 314 of Bible 365 — John 1-7',
  'bible-365-day-315': 'Day 315 of Bible 365 — John 1-7',
  'bible-365-day-316': 'Day 316 of Bible 365 — John 8-14',
  'bible-365-day-317': 'Day 317 of Bible 365 — John 8-14',
  'bible-365-day-318': 'Day 318 of Bible 365 — John 8-14',
  'bible-365-day-319': 'Day 319 of Bible 365 — John 8-14',
  'bible-365-day-32':
    "The brother they sold for silver now rules Egypt - and from the throne he says not 'guilty,' but 'come near to me.' Forgiveness moves downward, from power to the powerless who wronged him.",
  'bible-365-day-320': 'Day 320 of Bible 365 — John 8-14',
  'bible-365-day-321': 'Day 321 of Bible 365 — John 8-14',
  'bible-365-day-322': 'Day 322 of Bible 365 — John 8-14',
  'bible-365-day-323': 'Day 323 of Bible 365 — John 15-21',
  'bible-365-day-324': 'Day 324 of Bible 365 — John 15-21',
  'bible-365-day-325': 'Day 325 of Bible 365 — John 15-21',
  'bible-365-day-326': 'Day 326 of Bible 365 — John 15-21',
  'bible-365-day-327': 'Day 327 of Bible 365 — John 15-21',
  'bible-365-day-328': 'Day 328 of Bible 365 — John 15-21',
  'bible-365-day-329': 'Day 329 of Bible 365 — John 15-21',
  'bible-365-day-33': 'Day 33 of Bible 365 — Genesis 50:15-21',
  'bible-365-day-330': 'Day 330 of Bible 365 — Acts 1-10',
  'bible-365-day-331': 'Day 331 of Bible 365 — Acts 1-10',
  'bible-365-day-332': 'Day 332 of Bible 365 — Acts 1-10',
  'bible-365-day-333': 'Day 333 of Bible 365 — Acts 1-10',
  'bible-365-day-334': 'Day 334 of Bible 365 — Acts 1-10',
  'bible-365-day-335': 'Day 335 of Bible 365 — Acts 1-10',
  'bible-365-day-336': 'Day 336 of Bible 365 — Acts 1-10',
  'bible-365-day-337': 'Day 337 of Bible 365 — Romans 1-8',
  'bible-365-day-338': 'Day 338 of Bible 365 — Romans 1-8',
  'bible-365-day-339': 'Day 339 of Bible 365 — Romans 1-8',
  'bible-365-day-34':
    'Joseph stands before the brothers who sold him and tells the story again — this time naming where God was. The retelling is the healing.',
  'bible-365-day-340': 'Day 340 of Bible 365 — Romans 1-8',
  'bible-365-day-341': 'Day 341 of Bible 365 — Romans 1-8',
  'bible-365-day-342': 'Day 342 of Bible 365 — Romans 1-8',
  'bible-365-day-343': 'Day 343 of Bible 365 — Romans 1-8',
  'bible-365-day-344': 'Day 344 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-345': 'Day 345 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-346': 'Day 346 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-347': 'Day 347 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-348': 'Day 348 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-349': 'Day 349 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-35':
    'Day 35 of Bible 365 — Sabbath. Joseph looks at the brothers who sold him and says it three times: God sent me. Today you stop trying to read your story while it is still being written, and rest.',
  'bible-365-day-350': 'Day 350 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-351': 'Day 351 of Bible 365 — Hebrews 11-12',
  'bible-365-day-352': 'Day 352 of Bible 365 — Hebrews 11-12',
  'bible-365-day-353': 'Day 353 of Bible 365 — Hebrews 11-12',
  'bible-365-day-354': 'Day 354 of Bible 365 — Hebrews 11-12',
  'bible-365-day-355': 'Day 355 of Bible 365 — Hebrews 11-12',
  'bible-365-day-356': 'Day 356 of Bible 365 — Hebrews 11-12',
  'bible-365-day-357': 'Day 357 of Bible 365 — Hebrews 11-12',
  'bible-365-day-358': 'Day 358 of Bible 365 — Revelation 21-22',
  'bible-365-day-359': 'Day 359 of Bible 365 — Revelation 21-22',
  'bible-365-day-36':
    'Day 36 of Bible 365 — Exodus 1-2. A new king forgets Joseph, an empire builds itself on Hebrew backs, and for chapters God seems silent. Then a wordless groan goes up, and heaven moves.',
  'bible-365-day-360': 'Day 360 of Bible 365 — Revelation 21-22',
  'bible-365-day-361': 'Day 361 of Bible 365 — Revelation 21-22',
  'bible-365-day-362': 'Day 362 of Bible 365 — Revelation 21-22',
  'bible-365-day-363': 'Day 363 of Bible 365 — Revelation 21-22',
  'bible-365-day-364': 'Day 364 of Bible 365 — Revelation 21-22',
  'bible-365-day-365': 'Day 365 of Bible 365 — Revelation 22:20-21',
  'bible-365-day-37': 'Day 37 of Bible 365 — Exodus 3:1-15',
  'bible-365-day-38':
    'Moses begs God to send someone else. God does — but not the way Moses meant. The mouth he could not be, God would one day become.',
  'bible-365-day-39':
    "Day 39 of Bible 365 — Exodus 7-11. The plagues are not tantrums. They are God walking down the list of Egypt's gods, one by one, and proving each one empty.",
  'bible-365-day-4':
    "Day 4 of Bible 365 — Genesis 2:18-25. The first thing God ever called 'not good' was a person by themselves. Communion was the design, not the consolation.",
  'bible-365-day-40': 'Day 40 of Bible 365 — Exodus 12:1-13',
  'bible-365-day-41':
    "Day 41 of Bible 365 — Pharaoh's hardened heart and the mystery of judgment. The same God who hardened a heart to display His name would one day display that name by giving His own Son up to death.",
  'bible-365-day-42':
    'Trapped between Pharaoh and the sea, Israel is told to do the one thing terror cannot: be still. Salvation is something you watch God accomplish.',
  'bible-365-day-43':
    'Trapped between Pharaoh and the sea, Israel is told to do the one thing that feels like nothing: stand still. Salvation is something you watch God accomplish, not something you achieve.',
  'bible-365-day-44':
    "Israel walks out of the sea and the first thing they do is sing. The Bible's oldest song is not a hymn of theory but a survivor's cry — and one word in it is already a name.",
  'bible-365-day-45':
    'In the desert between rescue and rest, God rains bread from the sky — but only enough for today. The miracle is also a test: can a freed people learn to trust a God who feeds them one morning at a time?',
  'bible-365-day-46': 'Day 46 of Bible 365 — Exodus 17:1-7',
  'bible-365-day-47': 'Day 47 of Bible 365 — Exodus 19',
  'bible-365-day-48':
    'Before God gives a single command, He says who He is and what He has already done. The Ten Words open not with a demand but with a deliverance.',
  'bible-365-day-49':
    'The commandment that could not save you was never powerless because it was bad. It was powerless because you are weak. So God did the one thing the law could not: He came.',
  'bible-365-day-5':
    'The first lie did not deny God. It rephrased Him. Four words still rearrange faith into doubt: Did God really say?',
  'bible-365-day-50':
    "God's first home among His people is not a fortress He builds, but a tent they bring Him by hand. Before He gives the blueprint, He names the reason: that I may dwell among them.",
  'bible-365-day-51': 'Day 51 of Bible 365 — Exodus 32',
  'bible-365-day-52': 'Day 52 of Bible 365 — Exodus 33:12-23',
  'bible-365-day-53':
    'Once a year, on the only day Israel could not work, two goats stood for one mercy: blood carried in, sin carried out. The whole gospel is rehearsed in a single morning.',
  'bible-365-day-54': 'Day 54 of Bible 365 — Leviticus 19:1-18',
  'bible-365-day-55':
    "The oldest words ever prayed over God's people are not advice but a gift — the LORD's own face, turned toward you. And the last thing Jesus did before heaven was lift His hands and say them.",
  'bible-365-day-56':
    'Day 56 of Bible 365 — Sabbath. God hands Aaron the words to bless His people, then signs them Himself: His Name laid on them, His face turned toward them.',
  'bible-365-day-57':
    'Day 57 of Bible 365 — Numbers 13-14. Ten men saw giants. Two saw bread. The land was the same; the difference was who they thought was walking with them.',
  'bible-365-day-58':
    'Korah wanted the priesthood for himself. When the plague broke loose, it was the priest he envied who ran into the dying and stopped death with his own body.',
  'bible-365-day-59': 'Day 59 of Bible 365 — Numbers 21:4-9',
  'bible-365-day-6':
    'The first promise of the Gospel, hidden inside a curse, and the long road from Eden to the empty tomb.',
  'bible-365-day-60':
    'A king hires a prophet to curse Israel. Four times the curse is loaded; four times it comes out a blessing. You cannot pronounce against what God has decided to bless.',
  'bible-365-day-61': 'Day 61 of Bible 365 — Deuteronomy 6:4-9',
  'bible-365-day-62': 'Day 62 of Bible 365 — Deuteronomy 30:11-20',
  'bible-365-day-63':
    "On the edge of the good land, Moses warns Israel: the danger isn't hunger. It's being full and forgetting who fed you.",
  'bible-365-day-64': 'Day 64 of Bible 365 — Joshua 1:1-9',
  'bible-365-day-65':
    'A foreign woman ties a scarlet cord in her window and her whole house is spared when the wall falls. The thread that saves the outsider runs all the way to Bethlehem.',
  'bible-365-day-66': 'Day 66 of Bible 365 — Joshua 3-4',
  'bible-365-day-67': 'Day 67 of Bible 365 — Joshua 6',
  'bible-365-day-68':
    "Day 68 of Bible 365 — Joshua 7. Israel loses a battle it should have won, and the reason is a cloak and some silver buried in the dirt of one man's tent. What we hide does not stay private.",
  'bible-365-day-69':
    'Day 69 of Bible 365 — Joshua 24. At Shechem, Joshua hands Israel a choice. But the choice rests on a covenant God already kept first.',
  'bible-365-day-7':
    "Before the gate closes behind Adam, God kills to clothe him. The first death in Scripture is God's, for our shame.",
  'bible-365-day-70':
    'Israel finally lays its head down in the land. Not one promise had failed. But the rest of a settled people still waited for a greater Joshua.',
  'bible-365-day-71':
    'One generation saw God split rivers and topple walls. The next had never met Him. The book of Judges begins with a funeral and a forgetting.',
  'bible-365-day-72':
    'A frightened man hides in a winepress, and the Angel of the LORD calls him a mighty man of valor. Strength was never his to begin with.',
  'bible-365-day-73':
    'Day 73 of Bible 365 — Judges 7. God thins an army to three hundred and hides the fire in breakable clay, so the victory can only be read one way.',
  'bible-365-day-74': 'Day 74 of Bible 365 — Judges 13-16',
  'bible-365-day-75':
    'Day 75 of Bible 365 — Ruth 1. A widow comes home empty, and a foreigner who owes her nothing refuses to let go. Loyal love walks into Bethlehem at the start of the harvest.',
  'bible-365-day-76':
    'At the gate, one kinsman says "I cannot." Another says "I am buying." The whole line to David — and to Christ — turns on a redeemer willing to pay.',
  'bible-365-day-77':
    'A Moabite widow no record should have kept gets the last word of the book — and the first word of a king. This is the Sabbath of the included.',
  'bible-365-day-78': 'Day 78 of Bible 365 — 1 Samuel 1',
  'bible-365-day-79': 'Day 79 of Bible 365 — 1 Samuel 3',
  'bible-365-day-8':
    'Day 8 of Bible 365 - Genesis 4:1-16. The first death in the Bible is not from the curse outside Eden but from the anger inside a brother. God warns Cain before he strikes: sin is crouching, and it can be mastered.',
  'bible-365-day-80':
    'Israel asks for a king like the nations have — and God tells Samuel the ache underneath the request: it is not Samuel they have rejected, but Me.',
  'bible-365-day-81': 'Day 81 of Bible 365 — 1 Samuel 15',
  'bible-365-day-82':
    'Samuel parades seven impressive sons past the prophet. God waits for the boy nobody bothered to call in from the sheep.',
  'bible-365-day-83':
    'Forty days an army stands frozen behind one line nobody will cross. Then a shepherd walks into the gap — and the whole battle hangs on a single life.',
  'bible-365-day-84':
    'Seven impressive sons stand in a row. God passes them all and sends for the boy nobody bothered to call in from the sheep.',
  'bible-365-day-85':
    'Day 85 of Bible 365 — in a dark cave, David holds the life of the man hunting him, and chooses a torn hem over a throne seized by blood.',
  'bible-365-day-86':
    'David offers God a cedar house. God answers by promising David a house no axe could ever fell — a throne that outlives every king who sits on it.',
  'bible-365-day-87':
    'David pronounces a death sentence on a stranger in a story — and then the prophet turns the verdict around. The judgment we are so quick to hand out is the one we were always standing under.',
  'bible-365-day-88': 'Day 88 of Bible 365 — Psalm 51',
  'bible-365-day-89': 'Day 89 of Bible 365 — Psalm 23',
  'bible-365-day-9':
    'When God looked at a world bent only toward evil, one man caught His eye. Genesis 6 holds the first time grace is named in all of Scripture.',
  'bible-365-day-90': 'Day 90 of Bible 365 — Psalm 22',
  'bible-365-day-91':
    'Day 91 of Bible 365 — Sabbath. The week ends where the cross does: with the worst said out loud, and the love that outlasts it.',
  'bible-365-day-92':
    'Offered anything, Solomon asks for a listening heart. Then he builds a house for a God no house can hold - and the whole reading leans toward the day God moves in for good.',
  'bible-365-day-93':
    'Given anything, Solomon asks for a heart that hears. Then he builds a house too small for God — and points, without knowing it, to the One in whom all the fullness would finally dwell.',
  'bible-365-day-94':
    'The wisest man who ever lived builds God the most glorious house on earth — then stands in the doorway and admits it cannot hold Him. Day 94 of Bible 365.',
  'bible-365-day-95':
    'Given one wish, Solomon asks not for long life or wealth but for a heart that listens. Then he builds God a house and admits it could never hold Him. Day 95 of Bible 365 — 1 Kings 3-8.',
  'bible-365-day-96':
    "Solomon asks for a listening heart, builds God a house, then admits the house can't hold Him. What he builds in stone, God will one day build in flesh.",
  'bible-365-day-97':
    'Solomon asks for one thing and is given everything; then he builds God a house and admits it cannot hold Him. Wisdom and a dwelling place both point past themselves to Christ.',
  'bible-365-day-98':
    'Solomon asks for a listening heart, then builds God a house — and stands inside it knowing heaven itself cannot hold the One who came to dwell there.',
  'bible-365-day-99':
    "Solomon, the wisest king, drifts a thousand small steps from God. The kingdom tears. But a single tribe is held back — a lamp God refuses to extinguish for David's sake.",
  'coming-to-the-end-of-ourselves-day-1':
    'When our plans crumble, true faith finds its foundation',
  'coming-to-the-end-of-ourselves-day-2':
    "Discovering that God's care sustains us through suffering, not around it",
  'coming-to-the-end-of-ourselves-day-3':
    "When we stop asking 'Why me?' and start asking 'How can You use me?'",
  'coming-to-the-end-of-ourselves-day-4':
    'Loving God with everything we have left transforms what we have lost',
  'coming-to-the-end-of-ourselves-day-5':
    'Surrender is not defeat. It is the beginning of triumph in Christ.',
  'community-day-1':
    'Institutions are collapsing. Networks are transactional. So when it all falls apart, who actually stays?',
  'community-day-2':
    "We're more connected than ever and more isolated than ever. The loneliness is crushing. How did we get here?",
  'community-day-3':
    "The pivot: Jesus didn't build an empire. He built a table. Where two or three gather, He is there.",
  'community-day-4':
    'Not theory. Practice. The early church pooled resources, shared meals, and stayed when empire collapsed. Can we?',
  'community-day-5':
    'Systems are failing. Networks scatter. But covenant people stay. These are your people. And you are theirs.',
  'genesis-two-stories-of-creation-day-1':
    "God's creative power revealed as both cosmic King and personal Potter",
  'genesis-two-stories-of-creation-day-2':
    'Understanding our calling as image-bearers of God',
  'genesis-two-stories-of-creation-day-3':
    'The intimate, life-giving nature of our Creator',
  'genesis-two-stories-of-creation-day-4':
    'Our calling to be co-gardeners with God',
  'genesis-two-stories-of-creation-day-5':
    'The mystery of human community and partnership',
  'hearing-god-in-the-noise-day-1':
    "Learning to recognize Jesus' voice amid competing voices",
  'hearing-god-in-the-noise-day-2':
    "Learning to test spiritual messages against God's truth",
  'hearing-god-in-the-noise-day-3':
    "Learning to hear God's gentle whisper in the stillness",
  'hearing-god-in-the-noise-day-4':
    "Discovering God's living voice through His Word",
  'hearing-god-in-the-noise-day-5':
    "Learning to distinguish God's guidance from emotional impulses",
  'hearing-god-in-the-noise-day-6':
    'Establishing daily practices for consistent communion with God',
  'hope-day-1':
    'Optimism is dead. Toxic positivity fails. 57% are pessimistic about the future. So what do we do when hope feels like a lie?',
  'hope-day-2':
    "The honesty of lament. Permission to grieve. The psalmists didn't fake joy—they screamed at God and called it worship.",
  'hope-day-3':
    "The pivot: Jesus in Gethsemane and on the cross. Hope that doesn't skip the terror but walks through it.",
  'hope-day-4':
    'Application: The habits of hope. Practicing trust when the future is uncertain. Small acts of faithfulness in the dark.',
  'hope-day-5':
    'Resolution: Hope as the certainty of resurrection, not the certainty of outcomes. God makes all things new—even in 2026.',
  'identity-crisis-day-1':
    'Your country, your job, your security—all unstable. So who are you, really?',
  'identity-crisis-day-2':
    'Your five-year plan is obsolete. Your career path is blocked. The narrative is breaking down.',
  'identity-crisis-day-3':
    'The pivot: When performance fails, identity remains. You are named before you are productive.',
  'identity-crisis-day-4':
    'You know who you are now. But how do you actually live that way when the world demands proof?',
  'identity-crisis-day-5':
    "Everything unstable has been shaken. What remains is what's real. You are still here. You are still His.",
  'kingdom-day-1':
    "You're searching for refuge in empires, markets, and curated spirituality. But what if you're looking in the wrong places?",
  'kingdom-day-2':
    'The exhaustion of trying to find security in systems that are collapsing around you.',
  'kingdom-day-3':
    "THE PIVOT: You've been searching for a future kingdom. But Jesus said it's already here—present, accessible, now.",
  'kingdom-day-4':
    'Application: The kingdom is here. Now what? How do you actually live in it?',
  'kingdom-day-5':
    'Resolution: When the kingdom comes first, everything else falls into place. Not because you earned it. Because the kingdom provides.',
  'once-saved-always-saved-day-1':
    "Understanding Jesus's absolute promise that no one can snatch his sheep from his hand",
  'once-saved-always-saved-day-2':
    'Understanding the connection between abiding in Christ and bearing fruit',
  'once-saved-always-saved-day-3':
    'Understanding how first-century Christians distinguished genuine faith from false profession',
  'once-saved-always-saved-day-4':
    "Understanding God's comprehensive work in keeping believers secure",
  'once-saved-always-saved-day-5':
    "Understanding how to cooperate with God's grace in faithful living",
  'once-saved-always-saved-day-6':
    'Living with endurance when the race of faith is long and the challenges are real',
  'peace-day-1':
    "Your world is chaos. Your grip is tight. But control isn't bringing you peace.",
  'peace-day-2':
    "You're monitoring, planning, protecting. But the anxiety isn't easing—it's multiplying.",
  'peace-day-3':
    "The pivot: Jesus offers a peace that doesn't depend on controlling chaos. It depends on knowing the One who is sovereign over it.",
  'peace-day-4':
    "What does it look like to release your grip? To seek God's peace instead of manufactured stability?",
  'peace-day-5':
    "The world is still chaotic. But you're not holding it together anymore. God is. And that changes everything.",
  'present-in-the-chaos-day-1':
    "When busyness blinds you to God's presence, stillness becomes the cure",
  'present-in-the-chaos-day-2':
    'When purpose shapes your pace instead of pressure driving it',
  'present-in-the-chaos-day-3':
    'When provocation tests your roots, peace becomes your most powerful response',
  'present-in-the-chaos-day-4':
    'When critics question your motives, grace becomes your strongest defense',
  'present-in-the-chaos-day-5':
    'When your roots go deep enough, rising becomes natural',
  'provision-day-1':
    "Your pantry is full but you're still afraid. 47.9M food insecure while others stockpile. The scarcity mindset is killing us.",
  'provision-day-2':
    "The more you accumulate, the more you fear losing it. Fear is the engine of hoarding. And it's consuming you.",
  'provision-day-3':
    "The pivot: Five loaves feed 5,000. A widow's oil never runs out. Manna appears daily. In God's economy, sharing creates abundance.",
  'provision-day-4':
    "The early church didn't wait for institutions to solve poverty. They pooled resources. Shared meals. Made sure no one went without.",
  'provision-day-5':
    "You started hoarding out of fear. But you're ending with open hands. When you share what you have, everyone has enough.",
  'rooted-day-1':
    'When everything is stripped away, what remains is Christ living in you',
  'rooted-day-2': "How God's love grows when everything around you collapses",
  'rooted-day-3':
    'True quiet is not the absence of noise but the presence of God',
  'rooted-day-4':
    'God is not just sustaining you through the trial — He is transforming you in it',
  'rooted-day-5':
    'The depth of your roots determines the height of your rise — and your capacity to lift others',
  'signs-boldness-opposition-integrity-day-1':
    "Week 1 showed us the foundation of the early church. Week 2 shows us what happens the moment that foundation meets the world. In Acts 3-5, the movement of Jesus' followers becomes public. A miraculous healing at the Temple gate draws astonished crowds. Bold preaching by the apostles challenges the authorities. Opposition quickly rises. The young community's unity and integrity are tested. And through all of it, the name of Jesus proves unstoppable.",
  'signs-boldness-opposition-integrity-day-2':
    'Peter and John encounter a man who has been lame from birth. He expects money. Instead, he receives healing in the name of Jesus. This miracle is not merely compassionate — it is strategic. It is a sign that the ministry of Jesus has not ended. It has expanded.',
  'signs-boldness-opposition-integrity-day-3':
    'Peter and John stand before the most powerful religious authority in Israel. What they say next changes everything.',
  'signs-boldness-opposition-integrity-day-4':
    'Released from custody, Peter and John return to their community. What they pray for next reveals everything about what the early church valued.',
  'signs-boldness-opposition-integrity-day-5':
    'The apostles face arrest, an angel opens prison doors, and a Pharisee named Gamaliel offers the wisest counsel in Acts.',
  'standing-strong-day-1':
    "Discovering that doubt isn't the end of faith but the beginning of a deeper conversation with God",
  'standing-strong-day-2':
    "Discovering how setbacks become setups for God's greater purposes",
  'standing-strong-day-3':
    'Developing spiritual temperance when emotions threaten to overwhelm',
  'standing-strong-day-4':
    'Working out salvation through daily disciplines of prayer, Scripture, and service',
  'standing-strong-day-5':
    'How knowing Christ redefines what we count as gain and loss',
  'standing-strong-day-6':
    'Experiencing joy and peace that transcend understanding and guard our hearts',
  'standing-strong-day-7':
    "The secret of being content in any and every situation through Christ's strength",
  'surrender-to-gods-will-day-1':
    "True surrender isn't easy, but it's the pathway to God's greatest purposes",
  'surrender-to-gods-will-day-2':
    'Obedience to God flows naturally from a heart overwhelmed by His love',
  'surrender-to-gods-will-day-3':
    'True freedom comes not from doing whatever we want, but from being liberated to become who we were created to be',
  'surrender-to-gods-will-day-4':
    "Individual surrender to God's will transforms into community life that witnesses to the world",
  'surrender-to-gods-will-day-5':
    "Running from God's will doesn't lead to safety; it leads to a storm",
  'surrender-to-gods-will-day-6':
    'Our surrendered life together is the most compelling evidence that our God is real and His love transforms everything',
  'the-blueprint-of-community-day-1':
    'Jesus does not send His disciples out in their own strength - He promises real, Spirit-given power for a real mission',
  'the-blueprint-of-community-day-2':
    'The Holy Spirit descends to fill believers completely, enabling them to be witnesses to all nations',
  'the-blueprint-of-community-day-3':
    'The gospel confronts reality, requires a response, and creates community',
  'the-blueprint-of-community-day-4':
    'The four load-bearing commitments of a healthy church: teaching, fellowship, breaking of bread, and prayer',
  'the-blueprint-of-community-day-5':
    'The fruits of a Spirit-formed community: awe, generosity, unity, joy, hospitality, worship, and daily faithfulness',
  'the-nature-of-belief-day-1':
    'Understanding that trials produce perseverance and lead to spiritual maturity',
  'the-nature-of-belief-day-2':
    'Learning how to ask God for wisdom when trials expose our need',
  'the-nature-of-belief-day-3':
    'Understanding the requirement of believing without doubting',
  'the-nature-of-belief-day-4':
    'Recognizing how doubt undermines our prayers and expectations',
  'the-nature-of-belief-day-5':
    'Identifying and combating double-mindedness in our own lives',
  'the-nature-of-belief-day-6':
    "Applying the week's lessons on faith, trials, and single-minded devotion",
  'the-word-before-words-day-1':
    "God's first act in our chaos is not to fix it, but to be present in it",
  'the-word-before-words-day-2':
    'The first act of salvation is not a plan, but the arrival of light in our darkness',
  'the-word-before-words-day-3':
    "In the face of chaos, God's first act of salvation is to create a boundary where life can be preserved",
  'the-word-before-words-day-4':
    "When we lose our way, God's first gift is not a map, but a rhythm to live by",
  'the-word-before-words-day-5':
    "God's nature is not one of scarcity, but of extravagant generosity",
  'the-work-of-god-day-1':
    'Understanding that the work God requires is not religious activity but simple, profound belief',
  'the-work-of-god-day-2':
    'Understanding the difference between the temporary satisfaction the world offers and the true, life-giving sustenance that comes only from God',
  'the-work-of-god-day-3':
    "Jesus declares 'I am the bread of life' — the first of seven great 'I am' statements, claiming to be the ultimate source of spiritual satisfaction",
  'the-work-of-god-day-4':
    "Holding in tension the seemingly contradictory truths of God's sovereign choice and our personal responsibility to believe",
  'the-work-of-god-day-5':
    "Understanding the ultimate foundation of our security as believers and how God's will guarantees our eternal destiny",
  'the-work-of-god-day-6':
    'Bringing an 8-week journey to a close with a spirit of gratitude — the only appropriate response to the Bread of Life',
  'too-busy-for-god-day-1':
    'Recognizing that busyness without God is meaningless vapor',
  'too-busy-for-god-day-2': 'Learning to seek wisdom before hasty action',
  'too-busy-for-god-day-3':
    "Aligning activities with God's timing rather than human pressure",
  'too-busy-for-god-day-4':
    'Establishing reverence for God as the foundation of all wisdom',
  'too-busy-for-god-day-5': 'Choosing peaceful rest over anxious productivity',
  'too-busy-for-god-day-6': 'Actively remembering God throughout daily life',
  'truth-day-1':
    'Drowning in information but starving for truth. When nothing feels certain, where do you find solid ground?',
  'truth-day-2':
    'The deeper cost: constant distrust corrodes your ability to know anything at all.',
  'truth-day-3':
    "The pivot: Truth isn't information. It's incarnation. You're not looking for better data—you're looking for someone who doesn't lie.",
  'truth-day-4':
    "You don't need more facts. You need the wisdom to know what's true—and Who to trust.",
  'truth-day-5':
    'The resolution: You were never meant to navigate the fog alone. Truth has a name. And he knows yours.',
  'valued-day-1':
    "Discovering that God's love is not conditional on our physical perfection or circumstances",
  'valued-day-2':
    "How God's choice to use the weak reveals a radically different economy of worth",
  'valued-day-3':
    "How God's presence in our suffering reveals our value to Him",
  'valued-day-4':
    "How discovering God's purpose for your life reveals your true value to Him",
  'valued-day-5':
    "How understanding your value in God's eyes empowers you to help others discover theirs",
  'what-does-it-mean-to-believe-day-1':
    'Understanding the nature of doubt and what kind of evidence is convincing',
  'what-does-it-mean-to-believe-day-2':
    'When extraordinary claims are backed by extraordinary evidence, how do we process what that means?',
  'what-does-it-mean-to-believe-day-3':
    "How would first-century readers have understood Thomas's declaration, and what did it cost him to make it?",
  'what-does-it-mean-to-believe-day-4':
    "In our evidence-driven culture, what does Thomas's journey from skepticism to faith teach us about the nature of authentic belief?",
  'what-does-it-mean-to-believe-day-5':
    'If this investigation has convinced me that Jesus truly rose from the dead, what does that mean for how I live?',
  'what-does-it-mean-to-believe-day-6':
    "How do we live as people who have declared with Thomas, 'My Lord and my God!'?",
  'what-happens-when-you-repeatedly-sin-day-1':
    'Understanding the reality of internal conflict and ongoing sin struggle in the Christian life',
  'what-happens-when-you-repeatedly-sin-day-2':
    "How does God's promise of forgiveness connect to our experience of repeated failure and confession?",
  'what-happens-when-you-repeatedly-sin-day-3':
    "How did the early church understand the relationship between God's grace and moral responsibility?",
  'what-happens-when-you-repeatedly-sin-day-4':
    "How does God's power work through our weakness and repeated failures in the modern world?",
  'what-happens-when-you-repeatedly-sin-day-5':
    "What practical steps can I take to break cycles of repeated sin and walk in the Spirit's power?",
  'what-happens-when-you-repeatedly-sin-day-6':
    'How do I maintain hope and continue pressing forward when transformation seems slow and setbacks are frequent?',
  'what-is-carrying-a-cross-day-1':
    "Jesus's radical call to discipleship and its immediate context",
  'what-is-carrying-a-cross-day-2':
    "How Jesus's call fits into the larger biblical story of sacrifice and covenant",
  'what-is-carrying-a-cross-day-3':
    "Understanding what 'take up your cross' meant to first-century Jews under Roman occupation",
  'what-is-carrying-a-cross-day-4':
    'Applying cross-bearing discipleship to contemporary life in a consumer culture',
  'what-is-carrying-a-cross-day-5':
    'Moving from understanding to decision and commitment',
  'what-is-carrying-a-cross-day-6':
    'Building cross-bearing discipleship into the ongoing patterns of daily life',
  'what-is-christianity-day-1':
    'Most people have opinions about Christianity. Fewer have asked what it actually claims.',
  'what-is-christianity-day-2':
    'What if the thing keeping you from God is not your doubt — but your religion?',
  'what-is-christianity-day-3':
    'Grace offends the achiever because it renders the scoreboard irrelevant',
  'what-is-christianity-day-4':
    'What if recovery and faith have more in common than either side wants to admit?',
  'what-is-christianity-day-5':
    'Not a cleaned-up life. Not a perfect belief system. Something stranger and more durable than either.',
  'what-is-the-gospel-day-1':
    "Understanding Mark's urgent narrative style and the introduction of John the Baptist",
  'what-is-the-gospel-day-2':
    'Connecting Old Testament prophecy to Gospel fulfillment',
  'what-is-the-gospel-day-3':
    "Understanding the cultural and religious context of John's message",
  'what-is-the-gospel-day-4':
    'Applying the message of spiritual transformation to modern life',
  'what-is-the-gospel-day-5': 'Moving from investigation to personal decision',
  'what-is-the-gospel-day-6':
    'Living as people who actively prepare the way for ongoing transformation',
  'why-jesus-day-1': "What's Happening and Who's Involved?",
  'why-jesus-day-2': "What's the Connection?",
  'why-jesus-day-3': "What's the Lesson for the Original Audience?",
  'why-jesus-day-4': "What's the Lesson for Me Today?",
  'why-jesus-day-5': 'Personal Response',
  'why-jesus-day-6': 'Practical Application',
  'witness-under-pressure-expansion-day-1':
    'The gospel advances not in spite of pressure, but often through it',
  'witness-under-pressure-expansion-day-2':
    "The first major conflict in the church is not persecution but inequity, and the response defines the movement's health",
  'witness-under-pressure-expansion-day-3':
    'Stephen does not defend himself. He tells the truth. And that truth costs him his life.',
  'witness-under-pressure-expansion-day-4':
    'Persecution does not destroy the church. It plants it. Wherever believers go, they carry the message with them.',
  'witness-under-pressure-expansion-day-5':
    'Saul is not seeking Jesus. He is convinced he is serving God. And Jesus meets him anyway.',
}

export const DEVOTIONAL_TITLES: Record<string, string> = {
  'abiding-in-his-presence-day-1': 'From Visiting to Dwelling',
  'abiding-in-his-presence-day-2': 'Finding the Secret Place',
  'abiding-in-his-presence-day-3':
    "Making God's Presence Your Permanent Address",
  'abiding-in-his-presence-day-4': 'The Fruit of Abiding',
  'abiding-in-his-presence-day-5': 'Abiding in the Storms',
  'abiding-in-his-presence-day-6': 'Living the Abiding Life',
  'anointed-day-1': 'Anointed with Purpose',
  'anointed-day-2': 'Anointed with Power',
  'anointed-day-3': 'Anointed in Obscurity',
  'anointed-day-4': 'Anointed for Healing',
  'anointed-day-5': 'Anointed to Go',
  'bible-365-day-1': 'In the beginning, God',
  'bible-365-day-10': 'The covenant rainbow',
  'bible-365-day-100': 'The Heart That Was Never Whole',
  'bible-365-day-101': 'The slow theft of a divided heart',
  'bible-365-day-102': 'The slow theft of a divided heart',
  'bible-365-day-103': "Solomon's Drift — Day 5 — Resolution",
  'bible-365-day-104': 'The Heart That Drifted, the Lamp That Stayed',
  'bible-365-day-105': "The slow turning of a wise man's heart",
  'bible-365-day-106': 'The kingdom torn at Shechem',
  'bible-365-day-107': 'The kingdom tears, and a name is spoken',
  'bible-365-day-108': 'Too Far to Go Up',
  'bible-365-day-109': 'A nearer god, on your own terms',
  'bible-365-day-11': 'The name they could not build',
  'bible-365-day-110': 'Divided Kingdom — Day 5 — Resolution',
  'bible-365-day-111': 'Divided Kingdom — Day 6 — Deeper Dive',
  'bible-365-day-112': 'Divided Kingdom — Day 7 — Sabbath',
  'bible-365-day-113': 'The voice that was not in the fire',
  'bible-365-day-114': 'After the Fire, a Whisper',
  'bible-365-day-115': 'After the fire, a whisper',
  'bible-365-day-116': 'After the fire, the whisper',
  'bible-365-day-117': 'The mantle that fell',
  'bible-365-day-118': 'The God who was not in the fire',
  'bible-365-day-119': 'The God Who Was Not in the Fire',
  'bible-365-day-12': 'When language breaks',
  'bible-365-day-120': 'The jar that did not run dry',
  'bible-365-day-121': 'Wash and be clean',
  'bible-365-day-122': 'Wash and be clean',
  'bible-365-day-123': 'Bring the empty jars',
  'bible-365-day-124': 'Life that outlasts the grave',
  'bible-365-day-125': 'Wash, and be clean',
  'bible-365-day-126': 'Wash, and be clean',
  'bible-365-day-127': 'What the LORD Requires',
  'bible-365-day-128': 'Worship God Will Not Smell',
  'bible-365-day-129': 'What the LORD Requires',
  'bible-365-day-13': 'Go from your country',
  'bible-365-day-130': 'Three verbs the prophets would not let go',
  'bible-365-day-131': 'Northern Prophets — Day 5 — Resolution',
  'bible-365-day-132': 'When Mercy and Justice War Inside God',
  'bible-365-day-133': 'The Mercy God Wanted All Along',
  'bible-365-day-134': 'The king who tore his clothes and prayed',
  'bible-365-day-135': 'The Snake Hezekiah Broke',
  'bible-365-day-136': "Hezekiah's Reform — Day 3 — Pivot",
  'bible-365-day-137': "Hezekiah's Reform — Day 4 — Application",
  'bible-365-day-138': "Hezekiah's Reform — Day 5 — Resolution",
  'bible-365-day-139': "Hezekiah's Reform — Day 6 — Deeper Dive",
  'bible-365-day-14': 'What you leave to follow',
  'bible-365-day-140': "Hezekiah's Reform — Day 7 — Sabbath",
  'bible-365-day-141': 'Josiah Finds the Book — Day 1 — Hook',
  'bible-365-day-142': 'Josiah Finds the Book — Day 2 — Building',
  'bible-365-day-143': 'Josiah Finds the Book — Day 3 — Pivot',
  'bible-365-day-144': 'Josiah Finds the Book — Day 4 — Application',
  'bible-365-day-145': 'Josiah Finds the Book — Day 5 — Resolution',
  'bible-365-day-146': 'Josiah Finds the Book — Day 6 — Deeper Dive',
  'bible-365-day-147': 'Josiah Finds the Book — Day 7 — Sabbath',
  'bible-365-day-148': 'Jeremiah Weeping Prophet — Day 1 — Hook',
  'bible-365-day-149': 'Jeremiah Weeping Prophet — Day 2 — Building',
  'bible-365-day-15': 'He believed the Lord',
  'bible-365-day-150': 'Jeremiah Weeping Prophet — Day 3 — Pivot',
  'bible-365-day-151': 'Jeremiah Weeping Prophet — Day 4 — Application',
  'bible-365-day-152': 'Jeremiah Weeping Prophet — Day 5 — Resolution',
  'bible-365-day-153': 'Jeremiah Weeping Prophet — Day 6 — Deeper Dive',
  'bible-365-day-154': 'Jeremiah Weeping Prophet — Day 7 — Sabbath',
  'bible-365-day-155': 'Fall of Jerusalem + Lamentations — Day 1 — Hook',
  'bible-365-day-156': 'Fall of Jerusalem + Lamentations — Day 2 — Building',
  'bible-365-day-157': 'Fall of Jerusalem + Lamentations — Day 3 — Pivot',
  'bible-365-day-158': 'Fall of Jerusalem + Lamentations — Day 4 — Application',
  'bible-365-day-159': 'Fall of Jerusalem + Lamentations — Day 5 — Resolution',
  'bible-365-day-16': 'El Shaddai',
  'bible-365-day-160': 'Fall of Jerusalem + Lamentations — Day 6 — Deeper Dive',
  'bible-365-day-161': 'Fall of Jerusalem + Lamentations — Day 7 — Sabbath',
  'bible-365-day-162': 'Ezekiel Visions — Day 1 — Hook',
  'bible-365-day-163': 'Ezekiel Visions — Day 2 — Building',
  'bible-365-day-164': 'Ezekiel Visions — Day 3 — Pivot',
  'bible-365-day-165': 'Ezekiel Visions — Day 4 — Application',
  'bible-365-day-166': 'Ezekiel Visions — Day 5 — Resolution',
  'bible-365-day-167': 'Ezekiel Visions — Day 6 — Deeper Dive',
  'bible-365-day-168': 'Ezekiel Visions — Day 7 — Sabbath',
  'bible-365-day-169': 'Daniel’s Faithfulness — Day 1 — Hook',
  'bible-365-day-17': 'Three visitors at Mamre',
  'bible-365-day-170': 'Daniel’s Faithfulness — Day 2 — Building',
  'bible-365-day-171': 'Daniel’s Faithfulness — Day 3 — Pivot',
  'bible-365-day-172': 'Daniel’s Faithfulness — Day 4 — Application',
  'bible-365-day-173': 'Daniel’s Faithfulness — Day 5 — Resolution',
  'bible-365-day-174': 'Daniel’s Faithfulness — Day 6 — Deeper Dive',
  'bible-365-day-175': 'Daniel’s Faithfulness — Day 7 — Sabbath',
  'bible-365-day-176': 'Esther: For Such a Time — Day 1 — Hook',
  'bible-365-day-177': 'Esther: For Such a Time — Day 2 — Building',
  'bible-365-day-178': 'Esther: For Such a Time — Day 3 — Pivot',
  'bible-365-day-179': 'Esther: For Such a Time — Day 4 — Application',
  'bible-365-day-18': 'Will not the Judge do right?',
  'bible-365-day-180': 'Esther: For Such a Time — Day 5 — Resolution',
  'bible-365-day-181': 'Esther: For Such a Time — Day 6 — Deeper Dive',
  'bible-365-day-182': 'Esther: For Such a Time — Day 7 — Sabbath',
  'bible-365-day-183': 'Job: Suffering + Mystery — Day 1 — Hook',
  'bible-365-day-184': 'Job: Suffering + Mystery — Day 2 — Building',
  'bible-365-day-185': 'Job: Suffering + Mystery — Day 3 — Pivot',
  'bible-365-day-186': 'Job: Suffering + Mystery — Day 4 — Application',
  'bible-365-day-187': 'Job: Suffering + Mystery — Day 5 — Resolution',
  'bible-365-day-188': 'Job: Suffering + Mystery — Day 6 — Deeper Dive',
  'bible-365-day-189': 'Job: Suffering + Mystery — Day 7 — Sabbath',
  'bible-365-day-19': 'On the mountain it will be provided',
  'bible-365-day-190': 'Psalms of Trust — Day 1 — Hook',
  'bible-365-day-191': 'Psalms of Trust — Day 2 — Building',
  'bible-365-day-192': 'Psalms of Trust — Day 3 — Pivot',
  'bible-365-day-193': 'Psalms of Trust — Day 4 — Application',
  'bible-365-day-194': 'Psalms of Trust — Day 5 — Resolution',
  'bible-365-day-195': 'Psalms of Trust — Day 6 — Deeper Dive',
  'bible-365-day-196': 'Psalms of Trust — Day 7 — Sabbath',
  'bible-365-day-197': 'Proverbs: Daily Wisdom — Day 1 — Hook',
  'bible-365-day-198': 'Proverbs: Daily Wisdom — Day 2 — Building',
  'bible-365-day-199': 'Proverbs: Daily Wisdom — Day 3 — Pivot',
  'bible-365-day-2': 'Made in His image',
  'bible-365-day-20': 'Here I am, all the way up',
  'bible-365-day-200': 'Proverbs: Daily Wisdom — Day 4 — Application',
  'bible-365-day-201': 'Proverbs: Daily Wisdom — Day 5 — Resolution',
  'bible-365-day-202': 'Proverbs: Daily Wisdom — Day 6 — Deeper Dive',
  'bible-365-day-203': 'Proverbs: Daily Wisdom — Day 7 — Sabbath',
  'bible-365-day-204': 'Ecclesiastes: Vanity + God — Day 1 — Hook',
  'bible-365-day-205': 'Ecclesiastes: Vanity + God — Day 2 — Building',
  'bible-365-day-206': 'Ecclesiastes: Vanity + God — Day 3 — Pivot',
  'bible-365-day-207': 'Ecclesiastes: Vanity + God — Day 4 — Application',
  'bible-365-day-208': 'Ecclesiastes: Vanity + God — Day 5 — Resolution',
  'bible-365-day-209': 'Ecclesiastes: Vanity + God — Day 6 — Deeper Dive',
  'bible-365-day-21': 'Trust beyond comprehension',
  'bible-365-day-210': 'Ecclesiastes: Vanity + God — Day 7 — Sabbath',
  'bible-365-day-211': 'Song of Songs: Covenant Love — Day 1 — Hook',
  'bible-365-day-212': 'Song of Songs: Covenant Love — Day 2 — Building',
  'bible-365-day-213': 'Song of Songs: Covenant Love — Day 3 — Pivot',
  'bible-365-day-214': 'Song of Songs: Covenant Love — Day 4 — Application',
  'bible-365-day-215': 'Song of Songs: Covenant Love — Day 5 — Resolution',
  'bible-365-day-216': 'Song of Songs: Covenant Love — Day 6 — Deeper Dive',
  'bible-365-day-217': 'Song of Songs: Covenant Love — Day 7 — Sabbath',
  'bible-365-day-218': 'Isaiah: Holy One of Israel — Day 1 — Hook',
  'bible-365-day-219': 'Isaiah: Holy One of Israel — Day 2 — Building',
  'bible-365-day-22': 'Despising the birthright',
  'bible-365-day-220': 'Isaiah: Holy One of Israel — Day 3 — Pivot',
  'bible-365-day-221': 'Isaiah: Holy One of Israel — Day 4 — Application',
  'bible-365-day-222': 'Isaiah: Holy One of Israel — Day 5 — Resolution',
  'bible-365-day-223': 'Isaiah: Holy One of Israel — Day 6 — Deeper Dive',
  'bible-365-day-224': 'Isaiah: Holy One of Israel — Day 7 — Sabbath',
  'bible-365-day-225': 'Isaiah: Suffering Servant — Day 1 — Hook',
  'bible-365-day-226': 'Isaiah: Suffering Servant — Day 2 — Building',
  'bible-365-day-227': 'Isaiah: Suffering Servant — Day 3 — Pivot',
  'bible-365-day-228': 'Isaiah: Suffering Servant — Day 4 — Application',
  'bible-365-day-229': 'Isaiah: Suffering Servant — Day 5 — Resolution',
  'bible-365-day-23': "The ladder he didn't build",
  'bible-365-day-230': 'Isaiah: Suffering Servant — Day 6 — Deeper Dive',
  'bible-365-day-231': 'Isaiah: Suffering Servant — Day 7 — Sabbath',
  'bible-365-day-232': 'Jeremiah: New Covenant — Day 1 — Hook',
  'bible-365-day-233': 'Jeremiah: New Covenant — Day 2 — Building',
  'bible-365-day-234': 'Jeremiah: New Covenant — Day 3 — Pivot',
  'bible-365-day-235': 'Jeremiah: New Covenant — Day 4 — Application',
  'bible-365-day-236': 'Jeremiah: New Covenant — Day 5 — Resolution',
  'bible-365-day-237': 'Jeremiah: New Covenant — Day 6 — Deeper Dive',
  'bible-365-day-238': 'Jeremiah: New Covenant — Day 7 — Sabbath',
  'bible-365-day-239': 'Ezekiel: Dry Bones Live — Day 1 — Hook',
  'bible-365-day-24': 'The limp he kept',
  'bible-365-day-240': 'Ezekiel: Dry Bones Live — Day 2 — Building',
  'bible-365-day-241': 'Ezekiel: Dry Bones Live — Day 3 — Pivot',
  'bible-365-day-242': 'Ezekiel: Dry Bones Live — Day 4 — Application',
  'bible-365-day-243': 'Ezekiel: Dry Bones Live — Day 5 — Resolution',
  'bible-365-day-244': 'Ezekiel: Dry Bones Live — Day 6 — Deeper Dive',
  'bible-365-day-245': 'Ezekiel: Dry Bones Live — Day 7 — Sabbath',
  'bible-365-day-246': 'Daniel: Messiah Cut Off — Day 1 — Hook',
  'bible-365-day-247': 'Daniel: Messiah Cut Off — Day 2 — Building',
  'bible-365-day-248': 'Daniel: Messiah Cut Off — Day 3 — Pivot',
  'bible-365-day-249': 'Daniel: Messiah Cut Off — Day 4 — Application',
  'bible-365-day-25': 'I have seen God’s face',
  'bible-365-day-250': 'Daniel: Messiah Cut Off — Day 5 — Resolution',
  'bible-365-day-251': 'Daniel: Messiah Cut Off — Day 6 — Deeper Dive',
  'bible-365-day-252': 'Daniel: Messiah Cut Off — Day 7 — Sabbath',
  'bible-365-day-253': 'Hosea, Joel, Amos — Day 1 — Hook',
  'bible-365-day-254': 'Hosea, Joel, Amos — Day 2 — Building',
  'bible-365-day-255': 'Hosea, Joel, Amos — Day 3 — Pivot',
  'bible-365-day-256': 'Hosea, Joel, Amos — Day 4 — Application',
  'bible-365-day-257': 'Hosea, Joel, Amos — Day 5 — Resolution',
  'bible-365-day-258': 'Hosea, Joel, Amos — Day 6 — Deeper Dive',
  'bible-365-day-259': 'Hosea, Joel, Amos — Day 7 — Sabbath',
  'bible-365-day-26': 'Bury your idols',
  'bible-365-day-260': 'Jonah: Mercy on Enemies — Day 1 — Hook',
  'bible-365-day-261': 'Jonah: Mercy on Enemies — Day 2 — Building',
  'bible-365-day-262': 'Jonah: Mercy on Enemies — Day 3 — Pivot',
  'bible-365-day-263': 'Jonah: Mercy on Enemies — Day 4 — Application',
  'bible-365-day-264': 'Jonah: Mercy on Enemies — Day 5 — Resolution',
  'bible-365-day-265': 'Jonah: Mercy on Enemies — Day 6 — Deeper Dive',
  'bible-365-day-266': 'Jonah: Mercy on Enemies — Day 7 — Sabbath',
  'bible-365-day-267': 'Minor Prophets: Wait + Hope — Day 1 — Hook',
  'bible-365-day-268': 'Minor Prophets: Wait + Hope — Day 2 — Building',
  'bible-365-day-269': 'Minor Prophets: Wait + Hope — Day 3 — Pivot',
  'bible-365-day-27': 'Limp through life',
  'bible-365-day-270': 'Minor Prophets: Wait + Hope — Day 4 — Application',
  'bible-365-day-271': 'Minor Prophets: Wait + Hope — Day 5 — Resolution',
  'bible-365-day-272': 'Minor Prophets: Wait + Hope — Day 6 — Deeper Dive',
  'bible-365-day-273': 'Minor Prophets: Wait + Hope — Day 7 — Sabbath',
  'bible-365-day-274': 'Matthew: Kingdom Begins — Day 1 — Hook',
  'bible-365-day-275': 'Matthew: Kingdom Begins — Day 2 — Building',
  'bible-365-day-276': 'Matthew: Kingdom Begins — Day 3 — Pivot',
  'bible-365-day-277': 'Matthew: Kingdom Begins — Day 4 — Application',
  'bible-365-day-278': 'Matthew: Kingdom Begins — Day 5 — Resolution',
  'bible-365-day-279': 'Matthew: Kingdom Begins — Day 6 — Deeper Dive',
  'bible-365-day-28': 'What you wrestle for',
  'bible-365-day-280': 'Matthew: Kingdom Begins — Day 7 — Sabbath',
  'bible-365-day-281': 'Matthew: Parables + Miracles — Day 1 — Hook',
  'bible-365-day-282': 'Matthew: Parables + Miracles — Day 2 — Building',
  'bible-365-day-283': 'Matthew: Parables + Miracles — Day 3 — Pivot',
  'bible-365-day-284': 'Matthew: Parables + Miracles — Day 4 — Application',
  'bible-365-day-285': 'Matthew: Parables + Miracles — Day 5 — Resolution',
  'bible-365-day-286': 'Matthew: Parables + Miracles — Day 6 — Deeper Dive',
  'bible-365-day-287': 'Matthew: Parables + Miracles — Day 7 — Sabbath',
  'bible-365-day-288': 'Mark: The Suffering Servant — Day 1 — Hook',
  'bible-365-day-289': 'Mark: The Suffering Servant — Day 2 — Building',
  'bible-365-day-29': 'Sold by your brothers',
  'bible-365-day-290': 'Mark: The Suffering Servant — Day 3 — Pivot',
  'bible-365-day-291': 'Mark: The Suffering Servant — Day 4 — Application',
  'bible-365-day-292': 'Mark: The Suffering Servant — Day 5 — Resolution',
  'bible-365-day-293': 'Mark: The Suffering Servant — Day 6 — Deeper Dive',
  'bible-365-day-294': 'Mark: The Suffering Servant — Day 7 — Sabbath',
  'bible-365-day-295': 'Luke: The Inclusive Christ — Day 1 — Hook',
  'bible-365-day-296': 'Luke: The Inclusive Christ — Day 2 — Building',
  'bible-365-day-297': 'Luke: The Inclusive Christ — Day 3 — Pivot',
  'bible-365-day-298': 'Luke: The Inclusive Christ — Day 4 — Application',
  'bible-365-day-299': 'Luke: The Inclusive Christ — Day 5 — Resolution',
  'bible-365-day-3': 'The first sabbath',
  'bible-365-day-30': 'The Lord was with him',
  'bible-365-day-300': 'Luke: The Inclusive Christ — Day 6 — Deeper Dive',
  'bible-365-day-301': 'Luke: The Inclusive Christ — Day 7 — Sabbath',
  'bible-365-day-302': 'Luke: Lost-and-Found + Emmaus — Day 1 — Hook',
  'bible-365-day-303': 'Luke: Lost-and-Found + Emmaus — Day 2 — Building',
  'bible-365-day-304': 'Luke: Lost-and-Found + Emmaus — Day 3 — Pivot',
  'bible-365-day-305': 'Luke: Lost-and-Found + Emmaus — Day 4 — Application',
  'bible-365-day-306': 'Luke: Lost-and-Found + Emmaus — Day 5 — Resolution',
  'bible-365-day-307': 'Luke: Lost-and-Found + Emmaus — Day 6 — Deeper Dive',
  'bible-365-day-308': 'Luke: Lost-and-Found + Emmaus — Day 7 — Sabbath',
  'bible-365-day-309': 'John: The Word + I Ams — Day 1 — Hook',
  'bible-365-day-31': 'Pharaoh’s dream',
  'bible-365-day-310': 'John: The Word + I Ams — Day 2 — Building',
  'bible-365-day-311': 'John: The Word + I Ams — Day 3 — Pivot',
  'bible-365-day-312': 'John: The Word + I Ams — Day 4 — Application',
  'bible-365-day-313': 'John: The Word + I Ams — Day 5 — Resolution',
  'bible-365-day-314': 'John: The Word + I Ams — Day 6 — Deeper Dive',
  'bible-365-day-315': 'John: The Word + I Ams — Day 7 — Sabbath',
  'bible-365-day-316': 'John: True Vine + Way + Truth — Day 1 — Hook',
  'bible-365-day-317': 'John: True Vine + Way + Truth — Day 2 — Building',
  'bible-365-day-318': 'John: True Vine + Way + Truth — Day 3 — Pivot',
  'bible-365-day-319': 'John: True Vine + Way + Truth — Day 4 — Application',
  'bible-365-day-32': 'Come near, the one you sold',
  'bible-365-day-320': 'John: True Vine + Way + Truth — Day 5 — Resolution',
  'bible-365-day-321': 'John: True Vine + Way + Truth — Day 6 — Deeper Dive',
  'bible-365-day-322': 'John: True Vine + Way + Truth — Day 7 — Sabbath',
  'bible-365-day-323': 'John: Garden, Cross, Resurrection — Day 1 — Hook',
  'bible-365-day-324': 'John: Garden, Cross, Resurrection — Day 2 — Building',
  'bible-365-day-325': 'John: Garden, Cross, Resurrection — Day 3 — Pivot',
  'bible-365-day-326':
    'John: Garden, Cross, Resurrection — Day 4 — Application',
  'bible-365-day-327': 'John: Garden, Cross, Resurrection — Day 5 — Resolution',
  'bible-365-day-328':
    'John: Garden, Cross, Resurrection — Day 6 — Deeper Dive',
  'bible-365-day-329': 'John: Garden, Cross, Resurrection — Day 7 — Sabbath',
  'bible-365-day-33': 'You meant evil; God meant good',
  'bible-365-day-330': 'Acts: Pentecost + Spread — Day 1 — Hook',
  'bible-365-day-331': 'Acts: Pentecost + Spread — Day 2 — Building',
  'bible-365-day-332': 'Acts: Pentecost + Spread — Day 3 — Pivot',
  'bible-365-day-333': 'Acts: Pentecost + Spread — Day 4 — Application',
  'bible-365-day-334': 'Acts: Pentecost + Spread — Day 5 — Resolution',
  'bible-365-day-335': 'Acts: Pentecost + Spread — Day 6 — Deeper Dive',
  'bible-365-day-336': 'Acts: Pentecost + Spread — Day 7 — Sabbath',
  'bible-365-day-337': 'Romans: Justified by Faith — Day 1 — Hook',
  'bible-365-day-338': 'Romans: Justified by Faith — Day 2 — Building',
  'bible-365-day-339': 'Romans: Justified by Faith — Day 3 — Pivot',
  'bible-365-day-34': 'When trauma becomes testimony',
  'bible-365-day-340': 'Romans: Justified by Faith — Day 4 — Application',
  'bible-365-day-341': 'Romans: Justified by Faith — Day 5 — Resolution',
  'bible-365-day-342': 'Romans: Justified by Faith — Day 6 — Deeper Dive',
  'bible-365-day-343': 'Romans: Justified by Faith — Day 7 — Sabbath',
  'bible-365-day-344': '1 Corinthians: Love + Resurrection — Day 1 — Hook',
  'bible-365-day-345': '1 Corinthians: Love + Resurrection — Day 2 — Building',
  'bible-365-day-346': '1 Corinthians: Love + Resurrection — Day 3 — Pivot',
  'bible-365-day-347':
    '1 Corinthians: Love + Resurrection — Day 4 — Application',
  'bible-365-day-348':
    '1 Corinthians: Love + Resurrection — Day 5 — Resolution',
  'bible-365-day-349':
    '1 Corinthians: Love + Resurrection — Day 6 — Deeper Dive',
  'bible-365-day-35': 'Rest in providence',
  'bible-365-day-350': '1 Corinthians: Love + Resurrection — Day 7 — Sabbath',
  'bible-365-day-351': 'Hebrews: Faith Hall + Endurance — Day 1 — Hook',
  'bible-365-day-352': 'Hebrews: Faith Hall + Endurance — Day 2 — Building',
  'bible-365-day-353': 'Hebrews: Faith Hall + Endurance — Day 3 — Pivot',
  'bible-365-day-354': 'Hebrews: Faith Hall + Endurance — Day 4 — Application',
  'bible-365-day-355': 'Hebrews: Faith Hall + Endurance — Day 5 — Resolution',
  'bible-365-day-356': 'Hebrews: Faith Hall + Endurance — Day 6 — Deeper Dive',
  'bible-365-day-357': 'Hebrews: Faith Hall + Endurance — Day 7 — Sabbath',
  'bible-365-day-358': 'Revelation: New Heaven + New Earth — Day 1 — Hook',
  'bible-365-day-359': 'Revelation: New Heaven + New Earth — Day 2 — Building',
  'bible-365-day-36': 'A slave’s cry',
  'bible-365-day-360': 'Revelation: New Heaven + New Earth — Day 3 — Pivot',
  'bible-365-day-361':
    'Revelation: New Heaven + New Earth — Day 4 — Application',
  'bible-365-day-362':
    'Revelation: New Heaven + New Earth — Day 5 — Resolution',
  'bible-365-day-363':
    'Revelation: New Heaven + New Earth — Day 6 — Deeper Dive',
  'bible-365-day-364': 'Revelation: New Heaven + New Earth — Day 7 — Sabbath',
  'bible-365-day-365': 'Come, Lord Jesus',
  'bible-365-day-37': 'I AM that I AM',
  'bible-365-day-38': 'Slow of speech, sent anyway',
  'bible-365-day-39': 'Let my people go',
  'bible-365-day-4': 'Not good to be alone',
  'bible-365-day-40': 'The Passover lamb',
  'bible-365-day-41': 'The heart God hardened, the heart God broke',
  'bible-365-day-42': 'Rest in the rescue',
  'bible-365-day-43': 'Hemmed in, then opened',
  'bible-365-day-44': 'The first song was a rescue',
  'bible-365-day-45': 'Manna in the morning',
  'bible-365-day-46': 'Water from the rock',
  'bible-365-day-47': 'Sinai trembles',
  'bible-365-day-48': 'Rescued First, Then Commanded',
  'bible-365-day-49': 'What the law cannot do',
  'bible-365-day-5': "The serpent's question",
  'bible-365-day-50': 'A sanctuary for Me',
  'bible-365-day-51': 'The golden calf',
  'bible-365-day-52': 'Show me your glory',
  'bible-365-day-53': 'Two goats, one cleansing',
  'bible-365-day-54': 'Be holy as I am holy',
  'bible-365-day-55': 'The Lord bless you',
  'bible-365-day-56': 'When God’s face shines',
  'bible-365-day-57': 'Twelve scouts, two believers',
  'bible-365-day-58': 'The man who stood between the living and the dead',
  'bible-365-day-59': 'Bronze serpent lifted up',
  'bible-365-day-6': 'He will crush your head',
  'bible-365-day-60': 'The curse that would not fire',
  'bible-365-day-61': 'Hear, O Israel',
  'bible-365-day-62': 'Choose life',
  'bible-365-day-63': 'What we forget on the way',
  'bible-365-day-64': 'Be strong and courageous',
  'bible-365-day-65': 'Rahab’s red cord',
  'bible-365-day-66': 'Crossing into promise',
  'bible-365-day-67': 'Walls of Jericho',
  'bible-365-day-68': 'The thing buried under the tent',
  'bible-365-day-69': 'Choose this day',
  'bible-365-day-7': 'Cast out, but covered',
  'bible-365-day-70': 'Rest in the inheritance',
  'bible-365-day-71': 'After that generation',
  'bible-365-day-72': 'Gideon’s fleece',
  'bible-365-day-73': 'Three hundred',
  'bible-365-day-74': 'Samson’s strength + folly',
  'bible-365-day-75': 'Where you go, I will go',
  'bible-365-day-76': 'The redeemer who would not refuse',
  'bible-365-day-77': 'When God writes you in',
  'bible-365-day-78': 'Hannah’s tears',
  'bible-365-day-79': 'Speak, your servant hears',
  'bible-365-day-8': 'Sin crouches at the door',
  'bible-365-day-80': 'We want a king',
  'bible-365-day-81': 'To obey is better than sacrifice',
  'bible-365-day-82': 'Man looks at appearance',
  'bible-365-day-83': 'The Champion Who Goes Down Alone',
  'bible-365-day-84': 'When God chooses the overlooked',
  'bible-365-day-85': 'I will not lift my hand',
  'bible-365-day-86': 'You wanted to build Him a house',
  'bible-365-day-87': 'You are the man',
  'bible-365-day-88': 'Create in me a clean heart',
  'bible-365-day-89': 'The Lord is my shepherd',
  'bible-365-day-9': 'Noah found favor',
  'bible-365-day-90': 'My God, why?',
  'bible-365-day-91': 'After the worst, still loved',
  'bible-365-day-92': 'The king who asked to listen',
  'bible-365-day-93': 'He asked for a listening heart',
  'bible-365-day-94': 'A House That Cannot Hold Him',
  'bible-365-day-95': 'Ask for the listening heart',
  'bible-365-day-96': 'A House for a Name',
  'bible-365-day-97': 'A listening heart, a house too small for God',
  'bible-365-day-98': 'A house too small for God',
  'bible-365-day-99': 'The Lamp He Would Not Let Go Out',
  'coming-to-the-end-of-ourselves-day-1': 'The Breaking Point',
  'coming-to-the-end-of-ourselves-day-2': 'The Turning Point',
  'coming-to-the-end-of-ourselves-day-3': 'The Surrender',
  'coming-to-the-end-of-ourselves-day-4': 'The Purpose Revealed',
  'coming-to-the-end-of-ourselves-day-5': 'The Victory',
  'community-day-1': 'Who are your people when systems fail?',
  'community-day-2': 'What happens when everyone is a stranger?',
  'community-day-3': "What if you're not meant to be alone?",
  'community-day-4': 'What does covenant community actually look like?',
  'community-day-5': 'Who will remain when everything collapses?',
  'genesis-two-stories-of-creation-day-1': 'The Divine Zoom Lens',
  'genesis-two-stories-of-creation-day-2': 'Made in His Image',
  'genesis-two-stories-of-creation-day-3': 'The Breath of Life',
  'genesis-two-stories-of-creation-day-4': 'The Garden and the Gardener',
  'genesis-two-stories-of-creation-day-5': 'Created for Community',
  'hearing-god-in-the-noise-day-1': "Recognizing God's Voice",
  'hearing-god-in-the-noise-day-2': 'Filtering Spiritual Noise',
  'hearing-god-in-the-noise-day-3': "God's Whisper vs. Human Chaos",
  'hearing-god-in-the-noise-day-4': 'Hearing Through Scripture',
  'hearing-god-in-the-noise-day-5': "Discerning God's Voice vs. My Feelings",
  'hearing-god-in-the-noise-day-6': 'Building Rhythms of Grace',
  'hope-day-1': "What if hope isn't optimism, but faithfulness in the dark?",
  'hope-day-2': 'What if grief is holy?',
  'hope-day-3': 'What if hope enters the darkness instead of denying it?',
  'hope-day-4':
    "How do you practice faithfulness when you can't see the outcome?",
  'hope-day-5': 'What if hope is a resurrection promise, not blind optimism?',
  'identity-crisis-day-1':
    'When everything that defined you is shaken, who are you?',
  'identity-crisis-day-2':
    'What happens when the story you told yourself stops making sense?',
  'identity-crisis-day-3':
    "What if you're not what you do—you're whose you are?",
  'identity-crisis-day-4':
    'How do you live from identity instead of for identity?',
  'identity-crisis-day-5': 'Who will you be when the shaking stops?',
  'in-the-beginning-week-1-day-1': 'In the Beginning God Created',
  'in-the-beginning-week-1-day-2': 'The Spirit Hovering Over the Waters',
  'in-the-beginning-week-1-day-3': 'Let There Be Light',
  'in-the-beginning-week-1-day-4': 'God Saw That It Was Good',
  'in-the-beginning-week-1-day-5': 'The First Day',
  'in-the-beginning-week-1-day-6': 'Review and Practice',
  'kingdom-day-1': "What if the kingdom you're looking for is already here?",
  'kingdom-day-2': 'What happens when all your refuges fail?',
  'kingdom-day-3': 'The kingdom of God is in the midst of you',
  'kingdom-day-4': 'What does it look like to seek first the kingdom?',
  'kingdom-day-5': 'All these things will be added to you',
  'once-saved-always-saved-day-1': "What's Happening (and Who's Involved)?",
  'once-saved-always-saved-day-2': "What's the Connection?",
  'once-saved-always-saved-day-3':
    "What's the Lesson for the Original Audience?",
  'once-saved-always-saved-day-4': "What's the Lesson for Me Today?",
  'once-saved-always-saved-day-5': 'What Am I Going to Do About It?',
  'once-saved-always-saved-day-6':
    'Put It to Use: Running the Race with Perseverance',
  'peace-day-1': "What if peace isn't found by controlling your circumstances?",
  'peace-day-2': 'The exhaustion of managing everything',
  'peace-day-3': 'Peace I give you—not as the world gives',
  'peace-day-4': 'Practicing surrender over control',
  'peace-day-5': 'Peace as a kingdom gift, not an achievement',
  'present-in-the-chaos-day-1': 'Slowed to See',
  'present-in-the-chaos-day-2': 'Centered by Calling, Not Constant Motion',
  'present-in-the-chaos-day-3': 'Standing Firm Amid Pressure',
  'present-in-the-chaos-day-4': 'Grace Over Guilt',
  'present-in-the-chaos-day-5': 'Rooted to Rise',
  'provision-day-1':
    "What if provision isn't about having enough, but sharing what you have?",
  'provision-day-2': 'Why does having more make you feel less secure?',
  'provision-day-3': "What if God's economy works backwards?",
  'provision-day-4': 'What does mutual aid look like when the system fails?',
  'provision-day-5': 'What if sharing is how needs get met?',
  'rooted-day-1': 'Rooted in Truth',
  'rooted-day-2': 'Rooted in Love',
  'rooted-day-3': 'Rooted in Quiet',
  'rooted-day-4': 'Rooted in Struggle',
  'rooted-day-5': 'Rooted to Rise',
  'signs-boldness-opposition-integrity-day-1':
    'Signs, Boldness, Opposition, and Integrity',
  'signs-boldness-opposition-integrity-day-2': 'A Sign at the Beautiful Gate',
  'signs-boldness-opposition-integrity-day-3': 'Boldness Before the Council',
  'signs-boldness-opposition-integrity-day-4': 'A Prayer for Boldness',
  'signs-boldness-opposition-integrity-day-5':
    'When Integrity Meets Opposition',
  'standing-strong-day-1': 'Confident Faith',
  'standing-strong-day-2': 'Joy in Adversity',
  'standing-strong-day-3': 'Standing Firm',
  'standing-strong-day-4': 'Active Faith',
  'standing-strong-day-5': 'Transformed Perspective',
  'standing-strong-day-6': 'Supernatural Peace',
  'standing-strong-day-7': 'Contentment',
  'surrender-to-gods-will-day-1': 'The Agony of Surrender',
  'surrender-to-gods-will-day-2': 'The Love That Surrenders',
  'surrender-to-gods-will-day-3': 'The Freedom in Surrender',
  'surrender-to-gods-will-day-4': 'The Surrendered Community',
  'surrender-to-gods-will-day-5': 'The Cost of Non-Surrender',
  'surrender-to-gods-will-day-6': 'The Surrendered Life as a Witness',
  'the-blueprint-of-community-day-1': 'The Great Commission & the Upper Room',
  'the-blueprint-of-community-day-2': 'Pentecost & the Birth of the Church',
  'the-blueprint-of-community-day-3': "Peter's Sermon and the First Response",
  'the-blueprint-of-community-day-4': 'The Four Pillars of the New Community',
  'the-blueprint-of-community-day-5': 'Awe, Generosity, and Daily Rhythms',
  'the-nature-of-belief-day-1': 'The Purpose of Trials',
  'the-nature-of-belief-day-2': 'Asking for Wisdom',
  'the-nature-of-belief-day-3': 'The Condition of Faith',
  'the-nature-of-belief-day-4': 'The Danger of Doubt',
  'the-nature-of-belief-day-5': 'The Double-Minded Person',
  'the-nature-of-belief-day-6': 'Review and Application',
  'the-word-before-words-day-1': 'The Presence Before the Promise',
  'the-word-before-words-day-2': 'The Arrival of Light',
  'the-word-before-words-day-3': 'The First Boundary',
  'the-word-before-words-day-4': 'The Rhythm of Sacred Time',
  'the-word-before-words-day-5': 'The Explosion of Life',
  'the-work-of-god-day-1': 'The Work of God',
  'the-work-of-god-day-2': 'The Work of God',
  'the-work-of-god-day-3': 'The Work of God',
  'the-work-of-god-day-4': 'The Work of God',
  'the-work-of-god-day-5': 'The Work of God',
  'the-work-of-god-day-6': 'The Work of God',
  'too-busy-for-god-day-1': 'The Vanity of Busyness',
  'too-busy-for-god-day-2': 'Wisdom vs. Activity',
  'too-busy-for-god-day-3': 'Time and Seasons',
  'too-busy-for-god-day-4': 'The Fear of the Lord',
  'too-busy-for-god-day-5': 'Rest and Sabbath',
  'too-busy-for-god-day-6': 'Integration and Commitment',
  'truth-day-1':
    "How do you know what's real when misinformation is everywhere?",
  'truth-day-2': "When you can't trust anything, you can't trust yourself",
  'truth-day-3':
    "What if truth isn't a fact you verify—it's a person you know?",
  'truth-day-4': 'From information overload to wisdom: learning to discern',
  'truth-day-5': "Truth is a person, not a dataset—and he's waiting for you",
  'valued-day-1': 'Valued in Questions',
  'valued-day-2': 'Valued in Weakness',
  'valued-day-3': 'Valued in Suffering',
  'valued-day-4': 'Valued in Purpose',
  'valued-day-5': 'Valued to Value Others',
  'what-does-it-mean-to-believe-day-1': "The Skeptic's Demand",
  'what-does-it-mean-to-believe-day-2': 'When Evidence Meets Faith',
  'what-does-it-mean-to-believe-day-3': 'The Cost of Confession',
  'what-does-it-mean-to-believe-day-4':
    'Faith and Evidence in the Modern World',
  'what-does-it-mean-to-believe-day-5': 'From Investigation to Commitment',
  'what-does-it-mean-to-believe-day-6': 'Living the Confession',
  'what-happens-when-you-repeatedly-sin-day-1':
    "What's Happening (and Who's Involved)?",
  'what-happens-when-you-repeatedly-sin-day-2': "What's the Connection?",
  'what-happens-when-you-repeatedly-sin-day-3':
    "What's the Lesson for the Original Audience?",
  'what-happens-when-you-repeatedly-sin-day-4':
    "What's the Lesson for Me Today?",
  'what-happens-when-you-repeatedly-sin-day-5': 'What Will I Do?',
  'what-happens-when-you-repeatedly-sin-day-6': 'Review and Practice',
  'what-is-carrying-a-cross-day-1': 'The Call to Follow',
  'what-is-carrying-a-cross-day-2': 'The Cross Connection',
  'what-is-carrying-a-cross-day-3': 'The Original Audience',
  'what-is-carrying-a-cross-day-4': 'The Lesson for Me Today',
  'what-is-carrying-a-cross-day-5': 'What Am I Going to Do About It?',
  'what-is-carrying-a-cross-day-6': 'Put It to Use',
  'what-is-christianity-day-1': "The Question Everyone's Afraid to Ask",
  'what-is-christianity-day-2': 'When Religion Becomes a Cage',
  'what-is-christianity-day-3': "The God Who Doesn't Need Your Resume",
  'what-is-christianity-day-4': 'Free, Not Fixed',
  'what-is-christianity-day-5': 'A Faith Worth Having',
  'what-is-the-gospel-day-1': 'A Voice in the Wilderness',
  'what-is-the-gospel-day-2': 'The Ancient Path',
  'what-is-the-gospel-day-3': 'The Original Audience',
  'what-is-the-gospel-day-4': 'The Lesson for Me Today',
  'what-is-the-gospel-day-5': 'What Am I Going to Do About It?',
  'what-is-the-gospel-day-6': 'Put It to Use',
  'why-jesus-day-1': 'The Announcement',
  'why-jesus-day-2': 'The Promise Fulfilled',
  'why-jesus-day-3': 'The Original Audience',
  'why-jesus-day-4': 'The Lesson for Me Today',
  'why-jesus-day-5': 'What Am I Going to Do About It?',
  'why-jesus-day-6': 'Put It to Use',
  'witness-under-pressure-expansion-day-1':
    'Witness Under Pressure and Expansion Through Disruption',
  'witness-under-pressure-expansion-day-2': 'When Growth Creates Pressure',
  'witness-under-pressure-expansion-day-3': 'A Witness That Costs Everything',
  'witness-under-pressure-expansion-day-4': 'Scattered, Not Stopped',
  'witness-under-pressure-expansion-day-5': 'When God Interrupts the Enemy',
}

export function getDevotionalTeaser(slug: string): string | null {
  const t = DEVOTIONAL_TEASERS[slug]
  return t && t.length > 0 ? t : null
}

export function getDevotionalTitle(slug: string): string | null {
  const t = DEVOTIONAL_TITLES[slug]
  return t && t.length > 0 ? t : null
}
