// AUTO-GENERATED by scripts/generate-devotional-teasers.mjs
// Do not edit by hand. Re-run via `npm run build` (or the script directly).

export const DEVOTIONAL_TEASERS: Record<string, string> = {
  'abiding-in-his-presence-day-1':
    'Moving beyond spiritual visits to spiritual residence with God',
  'abiding-in-his-presence-day-2':
    "Discovering God's hidden refuge where we can be completely authentic and safe",
  'abiding-in-his-presence-day-3':
    'Understanding that God has permanently relocated to dwell with us',
  'abiding-in-his-presence-day-4':
    'Understanding that spiritual fruit is borne through connection, not produced through effort',
  'abiding-in-his-presence-day-5':
    "Maintaining connection to Jesus when life's pressures threaten to overwhelm",
  'abiding-in-his-presence-day-6':
    'Integrating continuous communion with God into every aspect of daily life',
  'anointed-day-1': "Your anointing isn't about position — it's about calling",
  'anointed-day-2':
    'The Holy Spirit empowers you for witness — not just words, but presence',
  'anointed-day-3':
    'Your hidden seasons are not wasted — they are the training ground for greatness',
  'anointed-day-4':
    "God's anointing is oil for wounds — His presence heals what is broken",
  'anointed-day-5': "Anointing is not to keep — it's to give. You are sent.",
  'bible-365-day-1':
    'A year-long walk through Scripture begins with four words that change everything: in the beginning, God.',
  'bible-365-day-10': 'Day 10 of Bible 365 — Genesis 8:20-9:17',
  'bible-365-day-100': 'Day 100 of Bible 365 — 1 Kings 11',
  'bible-365-day-101': 'Day 101 of Bible 365 — 1 Kings 11',
  'bible-365-day-102': 'Day 102 of Bible 365 — 1 Kings 11',
  'bible-365-day-103': 'Day 103 of Bible 365 — 1 Kings 11',
  'bible-365-day-104': 'Day 104 of Bible 365 — 1 Kings 11',
  'bible-365-day-105': 'Day 105 of Bible 365 — 1 Kings 11',
  'bible-365-day-106': 'Day 106 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-107': 'Day 107 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-108': 'Day 108 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-109': 'Day 109 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-11': 'Day 11 of Bible 365 — Genesis 11:1-9',
  'bible-365-day-110': 'Day 110 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-111': 'Day 111 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-112': 'Day 112 of Bible 365 — 1 Kings 12-16',
  'bible-365-day-113': 'Day 113 of Bible 365 — 1 Kings 17-19, 2 Kings 2',
  'bible-365-day-114': 'Day 114 of Bible 365 — 1 Kings 17-19, 2 Kings 2',
  'bible-365-day-115': 'Day 115 of Bible 365 — 1 Kings 17-19, 2 Kings 2',
  'bible-365-day-116': 'Day 116 of Bible 365 — 1 Kings 17-19, 2 Kings 2',
  'bible-365-day-117': 'Day 117 of Bible 365 — 1 Kings 17-19, 2 Kings 2',
  'bible-365-day-118': 'Day 118 of Bible 365 — 1 Kings 17-19, 2 Kings 2',
  'bible-365-day-119': 'Day 119 of Bible 365 — 1 Kings 17-19, 2 Kings 2',
  'bible-365-day-12': 'Day 12 of Bible 365 — Genesis 11 (recap)',
  'bible-365-day-120': 'Day 120 of Bible 365 — 2 Kings 4-13',
  'bible-365-day-121': 'Day 121 of Bible 365 — 2 Kings 4-13',
  'bible-365-day-122': 'Day 122 of Bible 365 — 2 Kings 4-13',
  'bible-365-day-123': 'Day 123 of Bible 365 — 2 Kings 4-13',
  'bible-365-day-124': 'Day 124 of Bible 365 — 2 Kings 4-13',
  'bible-365-day-125': 'Day 125 of Bible 365 — 2 Kings 4-13',
  'bible-365-day-126': 'Day 126 of Bible 365 — 2 Kings 4-13',
  'bible-365-day-127': 'Day 127 of Bible 365 — Amos, Hosea, Micah',
  'bible-365-day-128': 'Day 128 of Bible 365 — Amos, Hosea, Micah',
  'bible-365-day-129': 'Day 129 of Bible 365 — Amos, Hosea, Micah',
  'bible-365-day-13': 'Day 13 of Bible 365 — Genesis 12:1-3',
  'bible-365-day-130': 'Day 130 of Bible 365 — Amos, Hosea, Micah',
  'bible-365-day-131': 'Day 131 of Bible 365 — Amos, Hosea, Micah',
  'bible-365-day-132': 'Day 132 of Bible 365 — Amos, Hosea, Micah',
  'bible-365-day-133': 'Day 133 of Bible 365 — Amos, Hosea, Micah',
  'bible-365-day-134': 'Day 134 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-135': 'Day 135 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-136': 'Day 136 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-137': 'Day 137 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-138': 'Day 138 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-139': 'Day 139 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-14': 'Day 14 of Bible 365 — Genesis 12 (sabbath)',
  'bible-365-day-140': 'Day 140 of Bible 365 — 2 Kings 18-20',
  'bible-365-day-141': 'Day 141 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-142': 'Day 142 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-143': 'Day 143 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-144': 'Day 144 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-145': 'Day 145 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-146': 'Day 146 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-147': 'Day 147 of Bible 365 — 2 Kings 22-23',
  'bible-365-day-148': 'Day 148 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-149': 'Day 149 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-15': 'Day 15 of Bible 365 — Genesis 15:1-6',
  'bible-365-day-150': 'Day 150 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-151': 'Day 151 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-152': 'Day 152 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-153': 'Day 153 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-154': 'Day 154 of Bible 365 — Jeremiah 1-29',
  'bible-365-day-155': 'Day 155 of Bible 365 — Lamentations',
  'bible-365-day-156': 'Day 156 of Bible 365 — Lamentations',
  'bible-365-day-157': 'Day 157 of Bible 365 — Lamentations',
  'bible-365-day-158': 'Day 158 of Bible 365 — Lamentations',
  'bible-365-day-159': 'Day 159 of Bible 365 — Lamentations',
  'bible-365-day-16': 'Day 16 of Bible 365 — Genesis 17:1-8',
  'bible-365-day-160': 'Day 160 of Bible 365 — Lamentations',
  'bible-365-day-161': 'Day 161 of Bible 365 — Lamentations',
  'bible-365-day-162': 'Day 162 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-163': 'Day 163 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-164': 'Day 164 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-165': 'Day 165 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-166': 'Day 166 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-167': 'Day 167 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-168': 'Day 168 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-169': 'Day 169 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-17': 'Day 17 of Bible 365 — Genesis 18:1-15',
  'bible-365-day-170': 'Day 170 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-171': 'Day 171 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-172': 'Day 172 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-173': 'Day 173 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-174': 'Day 174 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-175': 'Day 175 of Bible 365 — Daniel 3, 6, 9',
  'bible-365-day-176': 'Day 176 of Bible 365 — Esther 4-7',
  'bible-365-day-177': 'Day 177 of Bible 365 — Esther 4-7',
  'bible-365-day-178': 'Day 178 of Bible 365 — Esther 4-7',
  'bible-365-day-179': 'Day 179 of Bible 365 — Esther 4-7',
  'bible-365-day-18': 'Day 18 of Bible 365 — Genesis 18:16-33',
  'bible-365-day-180': 'Day 180 of Bible 365 — Esther 4-7',
  'bible-365-day-181': 'Day 181 of Bible 365 — Esther 4-7',
  'bible-365-day-182': 'Day 182 of Bible 365 — Esther 4-7',
  'bible-365-day-183': 'Day 183 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-184': 'Day 184 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-185': 'Day 185 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-186': 'Day 186 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-187': 'Day 187 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-188': 'Day 188 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-189': 'Day 189 of Bible 365 — Job 1-2, 38-42',
  'bible-365-day-19': 'Day 19 of Bible 365 — Genesis 22:1-14',
  'bible-365-day-190':
    'Day 190 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-191':
    'Day 191 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-192':
    'Day 192 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-193':
    'Day 193 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-194':
    'Day 194 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-195':
    'Day 195 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-196':
    'Day 196 of Bible 365 — Psalm 1, 8, 19, 27, 90, 121, 130, 139',
  'bible-365-day-197': 'Day 197 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-198': 'Day 198 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-199': 'Day 199 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-2':
    'You did not earn your dignity. You were given it on the sixth day, before you ever did a thing.',
  'bible-365-day-20': 'Day 20 of Bible 365 — Genesis 22 (deeper)',
  'bible-365-day-200': 'Day 200 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-201': 'Day 201 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-202': 'Day 202 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-203': 'Day 203 of Bible 365 — Proverbs 3, 8, 16, 22, 31',
  'bible-365-day-204': 'Day 204 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-205': 'Day 205 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-206': 'Day 206 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-207': 'Day 207 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-208': 'Day 208 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-209': 'Day 209 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-21': 'Day 21 of Bible 365 — Genesis 22 (sabbath)',
  'bible-365-day-210': 'Day 210 of Bible 365 — Ecclesiastes 1, 3, 12',
  'bible-365-day-211': 'Day 211 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-212': 'Day 212 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-213': 'Day 213 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-214': 'Day 214 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-215': 'Day 215 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-216': 'Day 216 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-217': 'Day 217 of Bible 365 — Song 2, 6, 8',
  'bible-365-day-218': 'Day 218 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-219': 'Day 219 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-22': 'Day 22 of Bible 365 — Genesis 25:19-34',
  'bible-365-day-220': 'Day 220 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-221': 'Day 221 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-222': 'Day 222 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-223': 'Day 223 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-224': 'Day 224 of Bible 365 — Isaiah 6, 9, 11, 25',
  'bible-365-day-225': 'Day 225 of Bible 365 — Isaiah 40-55',
  'bible-365-day-226': 'Day 226 of Bible 365 — Isaiah 40-55',
  'bible-365-day-227': 'Day 227 of Bible 365 — Isaiah 40-55',
  'bible-365-day-228': 'Day 228 of Bible 365 — Isaiah 40-55',
  'bible-365-day-229': 'Day 229 of Bible 365 — Isaiah 40-55',
  'bible-365-day-23': 'Day 23 of Bible 365 — Genesis 28:10-22',
  'bible-365-day-230': 'Day 230 of Bible 365 — Isaiah 40-55',
  'bible-365-day-231': 'Day 231 of Bible 365 — Isaiah 40-55',
  'bible-365-day-232': 'Day 232 of Bible 365 — Jeremiah 31',
  'bible-365-day-233': 'Day 233 of Bible 365 — Jeremiah 31',
  'bible-365-day-234': 'Day 234 of Bible 365 — Jeremiah 31',
  'bible-365-day-235': 'Day 235 of Bible 365 — Jeremiah 31',
  'bible-365-day-236': 'Day 236 of Bible 365 — Jeremiah 31',
  'bible-365-day-237': 'Day 237 of Bible 365 — Jeremiah 31',
  'bible-365-day-238': 'Day 238 of Bible 365 — Jeremiah 31',
  'bible-365-day-239': 'Day 239 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-24': 'Day 24 of Bible 365 — Genesis 32:22-32',
  'bible-365-day-240': 'Day 240 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-241': 'Day 241 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-242': 'Day 242 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-243': 'Day 243 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-244': 'Day 244 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-245': 'Day 245 of Bible 365 — Ezekiel 36-37',
  'bible-365-day-246': 'Day 246 of Bible 365 — Daniel 7, 9',
  'bible-365-day-247': 'Day 247 of Bible 365 — Daniel 7, 9',
  'bible-365-day-248': 'Day 248 of Bible 365 — Daniel 7, 9',
  'bible-365-day-249': 'Day 249 of Bible 365 — Daniel 7, 9',
  'bible-365-day-25': 'Day 25 of Bible 365 — Genesis 33:1-11',
  'bible-365-day-250': 'Day 250 of Bible 365 — Daniel 7, 9',
  'bible-365-day-251': 'Day 251 of Bible 365 — Daniel 7, 9',
  'bible-365-day-252': 'Day 252 of Bible 365 — Daniel 7, 9',
  'bible-365-day-253': 'Day 253 of Bible 365 — Selected',
  'bible-365-day-254': 'Day 254 of Bible 365 — Selected',
  'bible-365-day-255': 'Day 255 of Bible 365 — Selected',
  'bible-365-day-256': 'Day 256 of Bible 365 — Selected',
  'bible-365-day-257': 'Day 257 of Bible 365 — Selected',
  'bible-365-day-258': 'Day 258 of Bible 365 — Selected',
  'bible-365-day-259': 'Day 259 of Bible 365 — Selected',
  'bible-365-day-26': 'Day 26 of Bible 365 — Genesis 35:1-15',
  'bible-365-day-260': 'Day 260 of Bible 365 — Jonah 1-4',
  'bible-365-day-261': 'Day 261 of Bible 365 — Jonah 1-4',
  'bible-365-day-262': 'Day 262 of Bible 365 — Jonah 1-4',
  'bible-365-day-263': 'Day 263 of Bible 365 — Jonah 1-4',
  'bible-365-day-264': 'Day 264 of Bible 365 — Jonah 1-4',
  'bible-365-day-265': 'Day 265 of Bible 365 — Jonah 1-4',
  'bible-365-day-266': 'Day 266 of Bible 365 — Jonah 1-4',
  'bible-365-day-267': 'Day 267 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-268': 'Day 268 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-269': 'Day 269 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-27': 'Day 27 of Bible 365 — Genesis (deeper)',
  'bible-365-day-270': 'Day 270 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-271': 'Day 271 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-272': 'Day 272 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-273': 'Day 273 of Bible 365 — Hab, Zeph, Hag, Zech, Mal',
  'bible-365-day-274': 'Day 274 of Bible 365 — Matthew 1-7',
  'bible-365-day-275': 'Day 275 of Bible 365 — Matthew 1-7',
  'bible-365-day-276': 'Day 276 of Bible 365 — Matthew 1-7',
  'bible-365-day-277': 'Day 277 of Bible 365 — Matthew 1-7',
  'bible-365-day-278': 'Day 278 of Bible 365 — Matthew 1-7',
  'bible-365-day-279': 'Day 279 of Bible 365 — Matthew 1-7',
  'bible-365-day-28': 'Day 28 of Bible 365 — Sabbath',
  'bible-365-day-280': 'Day 280 of Bible 365 — Matthew 1-7',
  'bible-365-day-281': 'Day 281 of Bible 365 — Matthew 8-13',
  'bible-365-day-282': 'Day 282 of Bible 365 — Matthew 8-13',
  'bible-365-day-283': 'Day 283 of Bible 365 — Matthew 8-13',
  'bible-365-day-284': 'Day 284 of Bible 365 — Matthew 8-13',
  'bible-365-day-285': 'Day 285 of Bible 365 — Matthew 8-13',
  'bible-365-day-286': 'Day 286 of Bible 365 — Matthew 8-13',
  'bible-365-day-287': 'Day 287 of Bible 365 — Matthew 8-13',
  'bible-365-day-288': 'Day 288 of Bible 365 — Mark 1-16',
  'bible-365-day-289': 'Day 289 of Bible 365 — Mark 1-16',
  'bible-365-day-29': 'Day 29 of Bible 365 — Genesis 37',
  'bible-365-day-290': 'Day 290 of Bible 365 — Mark 1-16',
  'bible-365-day-291': 'Day 291 of Bible 365 — Mark 1-16',
  'bible-365-day-292': 'Day 292 of Bible 365 — Mark 1-16',
  'bible-365-day-293': 'Day 293 of Bible 365 — Mark 1-16',
  'bible-365-day-294': 'Day 294 of Bible 365 — Mark 1-16',
  'bible-365-day-295': 'Day 295 of Bible 365 — Luke 1-12',
  'bible-365-day-296': 'Day 296 of Bible 365 — Luke 1-12',
  'bible-365-day-297': 'Day 297 of Bible 365 — Luke 1-12',
  'bible-365-day-298': 'Day 298 of Bible 365 — Luke 1-12',
  'bible-365-day-299': 'Day 299 of Bible 365 — Luke 1-12',
  'bible-365-day-3':
    'God finishes a universe and the next thing He does is stop. Before any human ever earned a paycheck, rest was already built into the shape of the week.',
  'bible-365-day-30': 'Day 30 of Bible 365 — Genesis 39',
  'bible-365-day-300': 'Day 300 of Bible 365 — Luke 1-12',
  'bible-365-day-301': 'Day 301 of Bible 365 — Luke 1-12',
  'bible-365-day-302': 'Day 302 of Bible 365 — Luke 15, 24',
  'bible-365-day-303': 'Day 303 of Bible 365 — Luke 15, 24',
  'bible-365-day-304': 'Day 304 of Bible 365 — Luke 15, 24',
  'bible-365-day-305': 'Day 305 of Bible 365 — Luke 15, 24',
  'bible-365-day-306': 'Day 306 of Bible 365 — Luke 15, 24',
  'bible-365-day-307': 'Day 307 of Bible 365 — Luke 15, 24',
  'bible-365-day-308': 'Day 308 of Bible 365 — Luke 15, 24',
  'bible-365-day-309': 'Day 309 of Bible 365 — John 1-7',
  'bible-365-day-31': 'Day 31 of Bible 365 — Genesis 41',
  'bible-365-day-310': 'Day 310 of Bible 365 — John 1-7',
  'bible-365-day-311': 'Day 311 of Bible 365 — John 1-7',
  'bible-365-day-312': 'Day 312 of Bible 365 — John 1-7',
  'bible-365-day-313': 'Day 313 of Bible 365 — John 1-7',
  'bible-365-day-314': 'Day 314 of Bible 365 — John 1-7',
  'bible-365-day-315': 'Day 315 of Bible 365 — John 1-7',
  'bible-365-day-316': 'Day 316 of Bible 365 — John 8-14',
  'bible-365-day-317': 'Day 317 of Bible 365 — John 8-14',
  'bible-365-day-318': 'Day 318 of Bible 365 — John 8-14',
  'bible-365-day-319': 'Day 319 of Bible 365 — John 8-14',
  'bible-365-day-32': 'Day 32 of Bible 365 — Genesis 45:1-15',
  'bible-365-day-320': 'Day 320 of Bible 365 — John 8-14',
  'bible-365-day-321': 'Day 321 of Bible 365 — John 8-14',
  'bible-365-day-322': 'Day 322 of Bible 365 — John 8-14',
  'bible-365-day-323': 'Day 323 of Bible 365 — John 15-21',
  'bible-365-day-324': 'Day 324 of Bible 365 — John 15-21',
  'bible-365-day-325': 'Day 325 of Bible 365 — John 15-21',
  'bible-365-day-326': 'Day 326 of Bible 365 — John 15-21',
  'bible-365-day-327': 'Day 327 of Bible 365 — John 15-21',
  'bible-365-day-328': 'Day 328 of Bible 365 — John 15-21',
  'bible-365-day-329': 'Day 329 of Bible 365 — John 15-21',
  'bible-365-day-33': 'Day 33 of Bible 365 — Genesis 50:15-21',
  'bible-365-day-330': 'Day 330 of Bible 365 — Acts 1-10',
  'bible-365-day-331': 'Day 331 of Bible 365 — Acts 1-10',
  'bible-365-day-332': 'Day 332 of Bible 365 — Acts 1-10',
  'bible-365-day-333': 'Day 333 of Bible 365 — Acts 1-10',
  'bible-365-day-334': 'Day 334 of Bible 365 — Acts 1-10',
  'bible-365-day-335': 'Day 335 of Bible 365 — Acts 1-10',
  'bible-365-day-336': 'Day 336 of Bible 365 — Acts 1-10',
  'bible-365-day-337': 'Day 337 of Bible 365 — Romans 1-8',
  'bible-365-day-338': 'Day 338 of Bible 365 — Romans 1-8',
  'bible-365-day-339': 'Day 339 of Bible 365 — Romans 1-8',
  'bible-365-day-34': 'Day 34 of Bible 365 — Genesis (deeper)',
  'bible-365-day-340': 'Day 340 of Bible 365 — Romans 1-8',
  'bible-365-day-341': 'Day 341 of Bible 365 — Romans 1-8',
  'bible-365-day-342': 'Day 342 of Bible 365 — Romans 1-8',
  'bible-365-day-343': 'Day 343 of Bible 365 — Romans 1-8',
  'bible-365-day-344': 'Day 344 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-345': 'Day 345 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-346': 'Day 346 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-347': 'Day 347 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-348': 'Day 348 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-349': 'Day 349 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-35': 'Day 35 of Bible 365 — Sabbath',
  'bible-365-day-350': 'Day 350 of Bible 365 — 1 Cor 13, 15',
  'bible-365-day-351': 'Day 351 of Bible 365 — Hebrews 11-12',
  'bible-365-day-352': 'Day 352 of Bible 365 — Hebrews 11-12',
  'bible-365-day-353': 'Day 353 of Bible 365 — Hebrews 11-12',
  'bible-365-day-354': 'Day 354 of Bible 365 — Hebrews 11-12',
  'bible-365-day-355': 'Day 355 of Bible 365 — Hebrews 11-12',
  'bible-365-day-356': 'Day 356 of Bible 365 — Hebrews 11-12',
  'bible-365-day-357': 'Day 357 of Bible 365 — Hebrews 11-12',
  'bible-365-day-358': 'Day 358 of Bible 365 — Revelation 21-22',
  'bible-365-day-359': 'Day 359 of Bible 365 — Revelation 21-22',
  'bible-365-day-36': 'Day 36 of Bible 365 — Exodus 1-2',
  'bible-365-day-360': 'Day 360 of Bible 365 — Revelation 21-22',
  'bible-365-day-361': 'Day 361 of Bible 365 — Revelation 21-22',
  'bible-365-day-362': 'Day 362 of Bible 365 — Revelation 21-22',
  'bible-365-day-363': 'Day 363 of Bible 365 — Revelation 21-22',
  'bible-365-day-364': 'Day 364 of Bible 365 — Revelation 21-22',
  'bible-365-day-365': 'Day 365 of Bible 365 — Revelation 22:20-21',
  'bible-365-day-37': 'Day 37 of Bible 365 — Exodus 3:1-15',
  'bible-365-day-38': 'Day 38 of Bible 365 — Exodus 4:10-17',
  'bible-365-day-39': 'Day 39 of Bible 365 — Exodus 7-11',
  'bible-365-day-4':
    'Day 4 of Bible 365 — Genesis 2:18-25. Communion is not a consolation. It was always the design.',
  'bible-365-day-40': 'Day 40 of Bible 365 — Exodus 12:1-13',
  'bible-365-day-41': 'Day 41 of Bible 365 — Exodus (deeper)',
  'bible-365-day-42': 'Day 42 of Bible 365 — Sabbath',
  'bible-365-day-43': 'Day 43 of Bible 365 — Exodus 14',
  'bible-365-day-44': 'Day 44 of Bible 365 — Exodus 15',
  'bible-365-day-45': 'Day 45 of Bible 365 — Exodus 16',
  'bible-365-day-46': 'Day 46 of Bible 365 — Exodus 17:1-7',
  'bible-365-day-47': 'Day 47 of Bible 365 — Exodus 19',
  'bible-365-day-48': 'Day 48 of Bible 365 — Exodus 20',
  'bible-365-day-49': 'Day 49 of Bible 365 — Sabbath',
  'bible-365-day-5':
    'The first lie did not deny God. It rephrased Him. Four words still rearrange faith into doubt: Did God really say?',
  'bible-365-day-50': 'Day 50 of Bible 365 — Exodus 25:1-9',
  'bible-365-day-51': 'Day 51 of Bible 365 — Exodus 32',
  'bible-365-day-52': 'Day 52 of Bible 365 — Exodus 33:12-23',
  'bible-365-day-53': 'Day 53 of Bible 365 — Leviticus 16',
  'bible-365-day-54': 'Day 54 of Bible 365 — Leviticus 19:1-18',
  'bible-365-day-55': 'Day 55 of Bible 365 — Numbers 6:22-27',
  'bible-365-day-56': 'Day 56 of Bible 365 — Sabbath',
  'bible-365-day-57': 'Day 57 of Bible 365 — Numbers 13-14',
  'bible-365-day-58': 'Day 58 of Bible 365 — Numbers 16',
  'bible-365-day-59': 'Day 59 of Bible 365 — Numbers 21:4-9',
  'bible-365-day-6':
    'The first promise of the Gospel, hidden inside a curse, and the long road from Eden to the empty tomb.',
  'bible-365-day-60': 'Day 60 of Bible 365 — Numbers 22-24',
  'bible-365-day-61': 'Day 61 of Bible 365 — Deuteronomy 6:4-9',
  'bible-365-day-62': 'Day 62 of Bible 365 — Deuteronomy 30:11-20',
  'bible-365-day-63': 'Day 63 of Bible 365 — Sabbath',
  'bible-365-day-64': 'Day 64 of Bible 365 — Joshua 1:1-9',
  'bible-365-day-65': 'Day 65 of Bible 365 — Joshua 2',
  'bible-365-day-66': 'Day 66 of Bible 365 — Joshua 3-4',
  'bible-365-day-67': 'Day 67 of Bible 365 — Joshua 6',
  'bible-365-day-68': 'Day 68 of Bible 365 — Joshua 7',
  'bible-365-day-69': 'Day 69 of Bible 365 — Joshua 24',
  'bible-365-day-7':
    'Day 7 of Bible 365 — God seeks Adam first, then clothes him. Mercy precedes the expulsion.',
  'bible-365-day-70': 'Day 70 of Bible 365 — Sabbath',
  'bible-365-day-71': 'Day 71 of Bible 365 — Judges 2:6-23',
  'bible-365-day-72': 'Day 72 of Bible 365 — Judges 6',
  'bible-365-day-73': 'Day 73 of Bible 365 — Judges 7',
  'bible-365-day-74': 'Day 74 of Bible 365 — Judges 13-16',
  'bible-365-day-75': 'Day 75 of Bible 365 — Ruth 1',
  'bible-365-day-76': 'Day 76 of Bible 365 — Ruth 4',
  'bible-365-day-77': 'Day 77 of Bible 365 — Sabbath',
  'bible-365-day-78': 'Day 78 of Bible 365 — 1 Samuel 1',
  'bible-365-day-79': 'Day 79 of Bible 365 — 1 Samuel 3',
  'bible-365-day-8': 'Day 8 of Bible 365 — Genesis 4:1-16',
  'bible-365-day-80': 'Day 80 of Bible 365 — 1 Samuel 8',
  'bible-365-day-81': 'Day 81 of Bible 365 — 1 Samuel 15',
  'bible-365-day-82': 'Day 82 of Bible 365 — 1 Samuel 16',
  'bible-365-day-83': 'Day 83 of Bible 365 — 1 Samuel 17',
  'bible-365-day-84': 'Day 84 of Bible 365 — Sabbath',
  'bible-365-day-85': 'Day 85 of Bible 365 — 1 Samuel 24',
  'bible-365-day-86': 'Day 86 of Bible 365 — 2 Samuel 7',
  'bible-365-day-87': 'Day 87 of Bible 365 — 2 Samuel 11-12',
  'bible-365-day-88': 'Day 88 of Bible 365 — Psalm 51',
  'bible-365-day-89': 'Day 89 of Bible 365 — Psalm 23',
  'bible-365-day-9': 'Day 9 of Bible 365 — Genesis 6:5-8',
  'bible-365-day-90': 'Day 90 of Bible 365 — Psalm 22',
  'bible-365-day-91': 'Day 91 of Bible 365 — Sabbath',
  'bible-365-day-92': 'Day 92 of Bible 365 — 1 Kings 3-8',
  'bible-365-day-93': 'Day 93 of Bible 365 — 1 Kings 3-8',
  'bible-365-day-94': 'Day 94 of Bible 365 — 1 Kings 3-8',
  'bible-365-day-95': 'Day 95 of Bible 365 — 1 Kings 3-8',
  'bible-365-day-96': 'Day 96 of Bible 365 — 1 Kings 3-8',
  'bible-365-day-97': 'Day 97 of Bible 365 — 1 Kings 3-8',
  'bible-365-day-98': 'Day 98 of Bible 365 — 1 Kings 3-8',
  'bible-365-day-99': 'Day 99 of Bible 365 — 1 Kings 11',
  'coming-to-the-end-of-ourselves-day-1':
    'When our plans crumble, true faith finds its foundation',
  'coming-to-the-end-of-ourselves-day-2':
    "Discovering that God's care sustains us through suffering, not around it",
  'coming-to-the-end-of-ourselves-day-3':
    "When we stop asking 'Why me?' and start asking 'How can You use me?'",
  'coming-to-the-end-of-ourselves-day-4':
    'Loving God with everything we have left transforms what we have lost',
  'coming-to-the-end-of-ourselves-day-5':
    'Surrender is not defeat. It is the beginning of triumph in Christ.',
  'community-day-1':
    'Institutions are collapsing. Networks are transactional. So when it all falls apart, who actually stays?',
  'community-day-2':
    "We're more connected than ever and more isolated than ever. The loneliness is crushing. How did we get here?",
  'community-day-3':
    "The pivot: Jesus didn't build an empire. He built a table. Where two or three gather, He is there.",
  'community-day-4':
    'Not theory. Practice. The early church pooled resources, shared meals, and stayed when empire collapsed. Can we?',
  'community-day-5':
    'Systems are failing. Networks scatter. But covenant people stay. These are your people. And you are theirs.',
  'genesis-two-stories-of-creation-day-1':
    "God's creative power revealed as both cosmic King and personal Potter",
  'genesis-two-stories-of-creation-day-2':
    'Understanding our calling as image-bearers of God',
  'genesis-two-stories-of-creation-day-3':
    'The intimate, life-giving nature of our Creator',
  'genesis-two-stories-of-creation-day-4':
    'Our calling to be co-gardeners with God',
  'genesis-two-stories-of-creation-day-5':
    'The mystery of human community and partnership',
  'hearing-god-in-the-noise-day-1':
    "Learning to recognize Jesus' voice amid competing voices",
  'hearing-god-in-the-noise-day-2':
    "Learning to test spiritual messages against God's truth",
  'hearing-god-in-the-noise-day-3':
    "Learning to hear God's gentle whisper in the stillness",
  'hearing-god-in-the-noise-day-4':
    "Discovering God's living voice through His Word",
  'hearing-god-in-the-noise-day-5':
    "Learning to distinguish God's guidance from emotional impulses",
  'hearing-god-in-the-noise-day-6':
    'Establishing daily practices for consistent communion with God',
  'hope-day-1':
    'Optimism is dead. Toxic positivity fails. 57% are pessimistic about the future. So what do we do when hope feels like a lie?',
  'hope-day-2':
    "The honesty of lament. Permission to grieve. The psalmists didn't fake joy—they screamed at God and called it worship.",
  'hope-day-3':
    "The pivot: Jesus in Gethsemane and on the cross. Hope that doesn't skip the terror but walks through it.",
  'hope-day-4':
    'Application: The habits of hope. Practicing trust when the future is uncertain. Small acts of faithfulness in the dark.',
  'hope-day-5':
    'Resolution: Hope as the certainty of resurrection, not the certainty of outcomes. God makes all things new—even in 2026.',
  'identity-crisis-day-1':
    'Your country, your job, your security—all unstable. So who are you, really?',
  'identity-crisis-day-2':
    'Your five-year plan is obsolete. Your career path is blocked. The narrative is breaking down.',
  'identity-crisis-day-3':
    'The pivot: When performance fails, identity remains. You are named before you are productive.',
  'identity-crisis-day-4':
    'You know who you are now. But how do you actually live that way when the world demands proof?',
  'identity-crisis-day-5':
    "Everything unstable has been shaken. What remains is what's real. You are still here. You are still His.",
  'kingdom-day-1':
    "You're searching for refuge in empires, markets, and curated spirituality. But what if you're looking in the wrong places?",
  'kingdom-day-2':
    'The exhaustion of trying to find security in systems that are collapsing around you.',
  'kingdom-day-3':
    "THE PIVOT: You've been searching for a future kingdom. But Jesus said it's already here—present, accessible, now.",
  'kingdom-day-4':
    'Application: The kingdom is here. Now what? How do you actually live in it?',
  'kingdom-day-5':
    'Resolution: When the kingdom comes first, everything else falls into place. Not because you earned it. Because the kingdom provides.',
  'once-saved-always-saved-day-1':
    "Understanding Jesus's absolute promise that no one can snatch his sheep from his hand",
  'once-saved-always-saved-day-2':
    'Understanding the connection between abiding in Christ and bearing fruit',
  'once-saved-always-saved-day-3':
    'Understanding how first-century Christians distinguished genuine faith from false profession',
  'once-saved-always-saved-day-4':
    "Understanding God's comprehensive work in keeping believers secure",
  'once-saved-always-saved-day-5':
    "Understanding how to cooperate with God's grace in faithful living",
  'once-saved-always-saved-day-6':
    'Living with endurance when the race of faith is long and the challenges are real',
  'peace-day-1':
    "Your world is chaos. Your grip is tight. But control isn't bringing you peace.",
  'peace-day-2':
    "You're monitoring, planning, protecting. But the anxiety isn't easing—it's multiplying.",
  'peace-day-3':
    "The pivot: Jesus offers a peace that doesn't depend on controlling chaos. It depends on knowing the One who is sovereign over it.",
  'peace-day-4':
    "What does it look like to release your grip? To seek God's peace instead of manufactured stability?",
  'peace-day-5':
    "The world is still chaotic. But you're not holding it together anymore. God is. And that changes everything.",
  'present-in-the-chaos-day-1':
    "When busyness blinds you to God's presence, stillness becomes the cure",
  'present-in-the-chaos-day-2':
    'When purpose shapes your pace instead of pressure driving it',
  'present-in-the-chaos-day-3':
    'When provocation tests your roots, peace becomes your most powerful response',
  'present-in-the-chaos-day-4':
    'When critics question your motives, grace becomes your strongest defense',
  'present-in-the-chaos-day-5':
    'When your roots go deep enough, rising becomes natural',
  'provision-day-1':
    "Your pantry is full but you're still afraid. 47.9M food insecure while others stockpile. The scarcity mindset is killing us.",
  'provision-day-2':
    "The more you accumulate, the more you fear losing it. Fear is the engine of hoarding. And it's consuming you.",
  'provision-day-3':
    "The pivot: Five loaves feed 5,000. A widow's oil never runs out. Manna appears daily. In God's economy, sharing creates abundance.",
  'provision-day-4':
    "The early church didn't wait for institutions to solve poverty. They pooled resources. Shared meals. Made sure no one went without.",
  'provision-day-5':
    "You started hoarding out of fear. But you're ending with open hands. When you share what you have, everyone has enough.",
  'rooted-day-1':
    'When everything is stripped away, what remains is Christ living in you',
  'rooted-day-2': "How God's love grows when everything around you collapses",
  'rooted-day-3':
    'True quiet is not the absence of noise but the presence of God',
  'rooted-day-4':
    'God is not just sustaining you through the trial — He is transforming you in it',
  'rooted-day-5':
    'The depth of your roots determines the height of your rise — and your capacity to lift others',
  'signs-boldness-opposition-integrity-day-1':
    "Week 1 showed us the foundation of the early church. Week 2 shows us what happens the moment that foundation meets the world. In Acts 3-5, the movement of Jesus' followers becomes public. A miraculous healing at the Temple gate draws astonished crowds. Bold preaching by the apostles challenges the authorities. Opposition quickly rises. The young community's unity and integrity are tested. And through all of it, the name of Jesus proves unstoppable.",
  'signs-boldness-opposition-integrity-day-2':
    'Peter and John encounter a man who has been lame from birth. He expects money. Instead, he receives healing in the name of Jesus. This miracle is not merely compassionate — it is strategic. It is a sign that the ministry of Jesus has not ended. It has expanded.',
  'signs-boldness-opposition-integrity-day-3':
    'Peter and John stand before the most powerful religious authority in Israel. What they say next changes everything.',
  'signs-boldness-opposition-integrity-day-4':
    'Released from custody, Peter and John return to their community. What they pray for next reveals everything about what the early church valued.',
  'signs-boldness-opposition-integrity-day-5':
    'The apostles face arrest, an angel opens prison doors, and a Pharisee named Gamaliel offers the wisest counsel in Acts.',
  'standing-strong-day-1':
    "Discovering that doubt isn't the end of faith but the beginning of a deeper conversation with God",
  'standing-strong-day-2':
    "Discovering how setbacks become setups for God's greater purposes",
  'standing-strong-day-3':
    'Developing spiritual temperance when emotions threaten to overwhelm',
  'standing-strong-day-4':
    'Working out salvation through daily disciplines of prayer, Scripture, and service',
  'standing-strong-day-5':
    'How knowing Christ redefines what we count as gain and loss',
  'standing-strong-day-6':
    'Experiencing joy and peace that transcend understanding and guard our hearts',
  'standing-strong-day-7':
    "The secret of being content in any and every situation through Christ's strength",
  'surrender-to-gods-will-day-1':
    "True surrender isn't easy, but it's the pathway to God's greatest purposes",
  'surrender-to-gods-will-day-2':
    'Obedience to God flows naturally from a heart overwhelmed by His love',
  'surrender-to-gods-will-day-3':
    'True freedom comes not from doing whatever we want, but from being liberated to become who we were created to be',
  'surrender-to-gods-will-day-4':
    "Individual surrender to God's will transforms into community life that witnesses to the world",
  'surrender-to-gods-will-day-5':
    "Running from God's will doesn't lead to safety; it leads to a storm",
  'surrender-to-gods-will-day-6':
    'Our surrendered life together is the most compelling evidence that our God is real and His love transforms everything',
  'the-blueprint-of-community-day-1':
    'Jesus does not send His disciples out in their own strength - He promises real, Spirit-given power for a real mission',
  'the-blueprint-of-community-day-2':
    'The Holy Spirit descends to fill believers completely, enabling them to be witnesses to all nations',
  'the-blueprint-of-community-day-3':
    'The gospel confronts reality, requires a response, and creates community',
  'the-blueprint-of-community-day-4':
    'The four load-bearing commitments of a healthy church: teaching, fellowship, breaking of bread, and prayer',
  'the-blueprint-of-community-day-5':
    'The fruits of a Spirit-formed community: awe, generosity, unity, joy, hospitality, worship, and daily faithfulness',
  'the-nature-of-belief-day-1':
    'Understanding that trials produce perseverance and lead to spiritual maturity',
  'the-nature-of-belief-day-2':
    'Learning how to ask God for wisdom when trials expose our need',
  'the-nature-of-belief-day-3':
    'Understanding the requirement of believing without doubting',
  'the-nature-of-belief-day-4':
    'Recognizing how doubt undermines our prayers and expectations',
  'the-nature-of-belief-day-5':
    'Identifying and combating double-mindedness in our own lives',
  'the-nature-of-belief-day-6':
    "Applying the week's lessons on faith, trials, and single-minded devotion",
  'the-word-before-words-day-1':
    "God's first act in our chaos is not to fix it, but to be present in it",
  'the-word-before-words-day-2':
    'The first act of salvation is not a plan, but the arrival of light in our darkness',
  'the-word-before-words-day-3':
    "In the face of chaos, God's first act of salvation is to create a boundary where life can be preserved",
  'the-word-before-words-day-4':
    "When we lose our way, God's first gift is not a map, but a rhythm to live by",
  'the-word-before-words-day-5':
    "God's nature is not one of scarcity, but of extravagant generosity",
  'the-work-of-god-day-1':
    'Understanding that the work God requires is not religious activity but simple, profound belief',
  'the-work-of-god-day-2':
    'Understanding the difference between the temporary satisfaction the world offers and the true, life-giving sustenance that comes only from God',
  'the-work-of-god-day-3':
    "Jesus declares 'I am the bread of life' — the first of seven great 'I am' statements, claiming to be the ultimate source of spiritual satisfaction",
  'the-work-of-god-day-4':
    "Holding in tension the seemingly contradictory truths of God's sovereign choice and our personal responsibility to believe",
  'the-work-of-god-day-5':
    "Understanding the ultimate foundation of our security as believers and how God's will guarantees our eternal destiny",
  'the-work-of-god-day-6':
    'Bringing an 8-week journey to a close with a spirit of gratitude — the only appropriate response to the Bread of Life',
  'too-busy-for-god-day-1':
    'Recognizing that busyness without God is meaningless vapor',
  'too-busy-for-god-day-2': 'Learning to seek wisdom before hasty action',
  'too-busy-for-god-day-3':
    "Aligning activities with God's timing rather than human pressure",
  'too-busy-for-god-day-4':
    'Establishing reverence for God as the foundation of all wisdom',
  'too-busy-for-god-day-5': 'Choosing peaceful rest over anxious productivity',
  'too-busy-for-god-day-6': 'Actively remembering God throughout daily life',
  'truth-day-1':
    'Drowning in information but starving for truth. When nothing feels certain, where do you find solid ground?',
  'truth-day-2':
    'The deeper cost: constant distrust corrodes your ability to know anything at all.',
  'truth-day-3':
    "The pivot: Truth isn't information. It's incarnation. You're not looking for better data—you're looking for someone who doesn't lie.",
  'truth-day-4':
    "You don't need more facts. You need the wisdom to know what's true—and Who to trust.",
  'truth-day-5':
    'The resolution: You were never meant to navigate the fog alone. Truth has a name. And he knows yours.',
  'valued-day-1':
    "Discovering that God's love is not conditional on our physical perfection or circumstances",
  'valued-day-2':
    "How God's choice to use the weak reveals a radically different economy of worth",
  'valued-day-3':
    "How God's presence in our suffering reveals our value to Him",
  'valued-day-4':
    "How discovering God's purpose for your life reveals your true value to Him",
  'valued-day-5':
    "How understanding your value in God's eyes empowers you to help others discover theirs",
  'what-does-it-mean-to-believe-day-1':
    'Understanding the nature of doubt and what kind of evidence is convincing',
  'what-does-it-mean-to-believe-day-2':
    'When extraordinary claims are backed by extraordinary evidence, how do we process what that means?',
  'what-does-it-mean-to-believe-day-3':
    "How would first-century readers have understood Thomas's declaration, and what did it cost him to make it?",
  'what-does-it-mean-to-believe-day-4':
    "In our evidence-driven culture, what does Thomas's journey from skepticism to faith teach us about the nature of authentic belief?",
  'what-does-it-mean-to-believe-day-5':
    'If this investigation has convinced me that Jesus truly rose from the dead, what does that mean for how I live?',
  'what-does-it-mean-to-believe-day-6':
    "How do we live as people who have declared with Thomas, 'My Lord and my God!'?",
  'what-happens-when-you-repeatedly-sin-day-1':
    'Understanding the reality of internal conflict and ongoing sin struggle in the Christian life',
  'what-happens-when-you-repeatedly-sin-day-2':
    "How does God's promise of forgiveness connect to our experience of repeated failure and confession?",
  'what-happens-when-you-repeatedly-sin-day-3':
    "How did the early church understand the relationship between God's grace and moral responsibility?",
  'what-happens-when-you-repeatedly-sin-day-4':
    "How does God's power work through our weakness and repeated failures in the modern world?",
  'what-happens-when-you-repeatedly-sin-day-5':
    "What practical steps can I take to break cycles of repeated sin and walk in the Spirit's power?",
  'what-happens-when-you-repeatedly-sin-day-6':
    'How do I maintain hope and continue pressing forward when transformation seems slow and setbacks are frequent?',
  'what-is-carrying-a-cross-day-1':
    "Jesus's radical call to discipleship and its immediate context",
  'what-is-carrying-a-cross-day-2':
    "How Jesus's call fits into the larger biblical story of sacrifice and covenant",
  'what-is-carrying-a-cross-day-3':
    "Understanding what 'take up your cross' meant to first-century Jews under Roman occupation",
  'what-is-carrying-a-cross-day-4':
    'Applying cross-bearing discipleship to contemporary life in a consumer culture',
  'what-is-carrying-a-cross-day-5':
    'Moving from understanding to decision and commitment',
  'what-is-carrying-a-cross-day-6':
    'Building cross-bearing discipleship into the ongoing patterns of daily life',
  'what-is-christianity-day-1':
    'Most people have opinions about Christianity. Fewer have asked what it actually claims.',
  'what-is-christianity-day-2':
    'What if the thing keeping you from God is not your doubt — but your religion?',
  'what-is-christianity-day-3':
    'Grace offends the achiever because it renders the scoreboard irrelevant',
  'what-is-christianity-day-4':
    'What if recovery and faith have more in common than either side wants to admit?',
  'what-is-christianity-day-5':
    'Not a cleaned-up life. Not a perfect belief system. Something stranger and more durable than either.',
  'what-is-the-gospel-day-1':
    "Understanding Mark's urgent narrative style and the introduction of John the Baptist",
  'what-is-the-gospel-day-2':
    'Connecting Old Testament prophecy to Gospel fulfillment',
  'what-is-the-gospel-day-3':
    "Understanding the cultural and religious context of John's message",
  'what-is-the-gospel-day-4':
    'Applying the message of spiritual transformation to modern life',
  'what-is-the-gospel-day-5': 'Moving from investigation to personal decision',
  'what-is-the-gospel-day-6':
    'Living as people who actively prepare the way for ongoing transformation',
  'why-jesus-day-1': "What's Happening and Who's Involved?",
  'why-jesus-day-2': "What's the Connection?",
  'why-jesus-day-3': "What's the Lesson for the Original Audience?",
  'why-jesus-day-4': "What's the Lesson for Me Today?",
  'why-jesus-day-5': 'Personal Response',
  'why-jesus-day-6': 'Practical Application',
  'witness-under-pressure-expansion-day-1':
    'The gospel advances not in spite of pressure, but often through it',
  'witness-under-pressure-expansion-day-2':
    "The first major conflict in the church is not persecution but inequity, and the response defines the movement's health",
  'witness-under-pressure-expansion-day-3':
    'Stephen does not defend himself. He tells the truth. And that truth costs him his life.',
  'witness-under-pressure-expansion-day-4':
    'Persecution does not destroy the church. It plants it. Wherever believers go, they carry the message with them.',
  'witness-under-pressure-expansion-day-5':
    'Saul is not seeking Jesus. He is convinced he is serving God. And Jesus meets him anyway.',
}

export function getDevotionalTeaser(slug: string): string | null {
  const t = DEVOTIONAL_TEASERS[slug]
  return t && t.length > 0 ? t : null
}
