/**
 * Auto-generated by scripts/build-substack-sources.ts +
 * scripts/cache-substack-images.ts.
 *
 * Maps each substack-sourced devotional slug → its canonical
 * Substack post URL + the post's primary header image. We now
 * cache the image locally under public/images/substack-cache/
 * (R35) and prefer the local path; substackImage retains the
 * substack-post-media S3 URL as a fallback in case the local
 * file isn't deployed.
 *
 * Do NOT edit by hand.
 */

export interface SubstackSource {
  substackUrl: string
  substackImage: string | null
  substackImageLocal: string | null
}

export const SUBSTACK_SOURCES: Record<string, SubstackSource> = {
  'abiding-in-his-presence-day-1': {
    substackUrl: 'https://wokegod.substack.com/p/abiding-in-his-presence-16',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/746715a6-c62c-4f52-85b1-02b12ef255e8_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/0b5fe7ad3f85.jpg',
  },
  'abiding-in-his-presence-day-2': {
    substackUrl: 'https://wokegod.substack.com/p/abiding-in-his-presence-26',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/685a4686-8ba6-48b2-8f93-d85def4b142a_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/1d0b58f9995f.jpg',
  },
  'abiding-in-his-presence-day-3': {
    substackUrl: 'https://wokegod.substack.com/p/abiding-in-his-presence-36',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/a1886067-91af-48ca-b45c-f0d47d00898b_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/9d6e9a96d9f1.jpg',
  },
  'abiding-in-his-presence-day-4': {
    substackUrl: 'https://wokegod.substack.com/p/abiding-in-his-presence-46',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/d54582bc-7edd-4626-ae24-fb4325215c7c_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/12981d6a5bc8.jpg',
  },
  'abiding-in-his-presence-day-5': {
    substackUrl: 'https://wokegod.substack.com/p/abiding-in-his-presence-56',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/3a8428e9-ddf7-4bf5-96ce-c4aae093e51c_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/9dabcb7af9ab.jpg',
  },
  'abiding-in-his-presence-day-6': {
    substackUrl: 'https://wokegod.substack.com/p/abiding-in-his-presence-66',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/1d41fc01-be2e-4633-b986-676c1f4d562a_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/e0ba93d09e54.jpg',
  },
  'genesis-two-stories-of-creation-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/genesis-two-stories-of-creation-deep',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/8af00a3f-6af0-40fd-8c38-82597e74080b_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/c1c3e6e777d3.jpg',
  },
  'genesis-two-stories-of-creation-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/genesis-two-stories-of-creation-day',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/25b012af-029b-49b4-b173-4b99fa44e6da_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/a36d7eff2ecc.jpg',
  },
  'genesis-two-stories-of-creation-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/genesis-two-stories-of-creation-day-340',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/9c3bbc81-9536-458f-90f5-264d97f750ab_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/be3109e2f5cc.jpg',
  },
  'genesis-two-stories-of-creation-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/genesis-two-stories-of-creation-day-a70',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/749f993d-bc8e-4623-92dd-cf662a8d7c4d_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/c2665ad3a2fc.jpg',
  },
  'genesis-two-stories-of-creation-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/genesis-two-stories-of-creation-day-a0f',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/5a59d320-2589-4efa-a1f6-c1bc64a29986_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/1cd5bce800ea.jpg',
  },
  'hearing-god-in-the-noise-day-1': {
    substackUrl: 'https://wokegod.substack.com/p/hearing-god-in-the-noise-16',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/19eff247-c038-487e-911e-b1781d49f05f_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/7688683f255e.jpg',
  },
  'hearing-god-in-the-noise-day-2': {
    substackUrl: 'https://wokegod.substack.com/p/hearing-god-in-the-noise-26',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/081db1a9-9c7d-45e1-aac6-d10f63c3649d_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/ffb49b740247.jpg',
  },
  'hearing-god-in-the-noise-day-3': {
    substackUrl: 'https://wokegod.substack.com/p/hearing-god-in-the-noise-36',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/cf1314fd-7f90-4ffd-995a-f043d33a6eae_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/adc0554c0bac.jpg',
  },
  'hearing-god-in-the-noise-day-4': {
    substackUrl: 'https://wokegod.substack.com/p/hearing-god-in-the-noise-46',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/0f3d4abc-22c9-4ad4-87d7-56c3c7367cec_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/5aaaf6a0706c.jpg',
  },
  'hearing-god-in-the-noise-day-5': {
    substackUrl: 'https://wokegod.substack.com/p/hearing-god-in-the-noise-56',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/5d448ad3-766e-4841-8f44-6b04681bdabd_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/0bd992fc30e2.jpg',
  },
  'hearing-god-in-the-noise-day-6': {
    substackUrl: 'https://wokegod.substack.com/p/hearing-god-in-the-noise-66',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/e439cade-9745-4d60-a21e-488641299706_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/a8e04d77f2db.jpg',
  },
  'in-the-beginning-week-1-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/in-the-beginning-week-1-the-god-who',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/ba6f67e4-c3d5-477c-a70c-0f4e71c4d3a1_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/8889fd8a4147.jpg',
  },
  'in-the-beginning-week-1-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/in-the-beginning-week-1-the-god-who-fac',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/7986068d-da42-44bd-b216-616b10ff24fa_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/24e920c138e3.jpg',
  },
  'in-the-beginning-week-1-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/in-the-beginning-week-1-the-god-who-c09',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/8d96a660-025c-463a-9705-955566ea3120_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/999176acfdd5.jpg',
  },
  'in-the-beginning-week-1-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/in-the-beginning-week-1-the-god-who-1fa',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/fc205f3a-c257-4052-8aab-f4676140dbea_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/4d03f10dd222.jpg',
  },
  'in-the-beginning-week-1-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/in-the-beginning-week-1-the-god-who-b48',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/afba881d-7e7a-4035-a494-1eb635025088_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/e28c219d540c.jpg',
  },
  'in-the-beginning-week-1-day-6': {
    substackUrl:
      'https://wokegod.substack.com/p/in-the-beginning-week-1-the-god-who-143',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/21a9e2a3-12ea-4eca-97e5-93febf2fbc43_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/c8711d0c6442.jpg',
  },
  'once-saved-always-saved-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/once-saved-always-saved-day-16-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/e54688e1-3f24-43d5-8ddb-3250f7b62329_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/1d5c4a5a7bfe.jpg',
  },
  'once-saved-always-saved-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/once-saved-always-saved-day-26-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/bc19dd4a-8ab0-4d09-8f60-6f799fd42537_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/f869a8b1ce79.jpg',
  },
  'once-saved-always-saved-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/once-saved-always-saved-day-36-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/0666941f-85e6-40ae-8456-94feb7af300d_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/d04618158208.jpg',
  },
  'once-saved-always-saved-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/once-saved-always-saved-day-46-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/7b177908-a7c6-45cf-ad06-60e88b5ee4ed_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/7251daa813d6.jpg',
  },
  'once-saved-always-saved-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/once-saved-always-saved-day-56-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/10b9d737-2eb2-436f-95b4-38bbe9aeca9c_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/986d9827e190.jpg',
  },
  'once-saved-always-saved-day-6': {
    substackUrl:
      'https://wokegod.substack.com/p/once-saved-always-saved-day-66-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/9d04c95b-70f3-44af-9e9d-85654580d375_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/0c84fde021da.jpg',
  },
  'surrender-to-gods-will-day-1': {
    substackUrl: 'https://wokegod.substack.com/p/surrender-to-gods-will-16',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/643edb5a-36f3-484b-9584-269a78ad771e_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/981ba5732006.jpg',
  },
  'surrender-to-gods-will-day-2': {
    substackUrl: 'https://wokegod.substack.com/p/surrender-to-gods-will-26',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/f7dd4c88-ff87-4692-a7d1-0a46daa00a0a_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/327323ced2ab.jpg',
  },
  'surrender-to-gods-will-day-3': {
    substackUrl: 'https://wokegod.substack.com/p/surrender-to-gods-will-36',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/8a87d929-43d0-4323-b57f-740c22deaadb_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/8eb3602d3c50.jpg',
  },
  'surrender-to-gods-will-day-4': {
    substackUrl: 'https://wokegod.substack.com/p/surrender-to-gods-will-46',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/a94d8c55-0293-4509-989e-2a3241c8887f_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/c8352b1d7894.jpg',
  },
  'surrender-to-gods-will-day-5': {
    substackUrl: 'https://wokegod.substack.com/p/surrender-to-gods-will-56',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/a2a3b42b-017b-4e68-b141-b9f324aefd7c_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/9bd0c3465600.jpg',
  },
  'surrender-to-gods-will-day-6': {
    substackUrl: 'https://wokegod.substack.com/p/surrender-to-gods-will-66',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/8f354d1d-0e8d-499d-8c2f-e037ec3768cc_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/0087ca30f891.jpg',
  },
  'the-blueprint-of-community-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/the-blueprint-of-community-deepdive',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/0ec295a9-8340-41d6-9a1f-802eb844ed78_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/fbaccfd8ad97.jpg',
  },
  'the-blueprint-of-community-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/the-blueprint-of-community-day-15',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/023657f9-7d66-4dac-8522-5bf3db55fa71_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/e441b0465fb1.jpg',
  },
  'the-blueprint-of-community-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/the-blueprint-of-community-day-25',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/d421f8b6-5345-42c6-86f9-7d2cedc7e950_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/b9afdeff4945.jpg',
  },
  'the-blueprint-of-community-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/the-blueprint-of-community-day-35',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/67707546-f0c5-4a67-9161-fb6ae2364631_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/b92e78151386.jpg',
  },
  'the-blueprint-of-community-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/the-blueprint-of-community-day-45',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/abeaaa6a-d90c-41be-b227-3cc139056e72_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/f98558c6be79.jpg',
  },
  'the-nature-of-belief-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/the-nature-of-belief-day-16-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/0f13816b-34c9-434d-a01a-c077bf24a496_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/a4693e80b14e.jpg',
  },
  'the-nature-of-belief-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/the-nature-of-belief-day-26-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/9042faf4-87d7-4266-9ec9-d0be19ea6980_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/e34f5299c541.jpg',
  },
  'the-nature-of-belief-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/the-nature-of-belief-day-36-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/f8790dae-5adc-4945-aa0f-12c195e0a253_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/37c65188c195.jpg',
  },
  'the-nature-of-belief-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/the-nature-of-belief-day-46-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/f6fadbc5-927a-464f-908e-b87da3f9317d_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/78b4e8df92f2.jpg',
  },
  'the-nature-of-belief-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/the-nature-of-belief-day-56-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/6246e6fb-b3e1-4e92-a072-8873b5d8bc34_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/98361fdc168b.jpg',
  },
  'the-nature-of-belief-day-6': {
    substackUrl:
      'https://wokegod.substack.com/p/the-nature-of-belief-day-66-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/72d479f2-e370-494f-b5ee-b86dcbccd657_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/1a93597281cc.jpg',
  },
  'the-word-before-words-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/the-word-before-words-week-1-deep',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/7acaaa4d-4845-4b65-8f05-25836321d29b_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/d65e0d9b324c.jpg',
  },
  'the-word-before-words-day-2': {
    substackUrl: 'https://wokegod.substack.com/p/the-word-before-words-day-15',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/ccfa2fc2-75be-47f0-98dc-faa2add3c775_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/09d5f061ad75.jpg',
  },
  'the-word-before-words-day-3': {
    substackUrl: 'https://wokegod.substack.com/p/the-word-before-words-day-25',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/c16f4ab5-4a0e-4024-ab06-70481e7246cf_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/6d5deb705175.jpg',
  },
  'the-word-before-words-day-4': {
    substackUrl: 'https://wokegod.substack.com/p/the-word-before-words-day-35',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/33d2a9ec-0c0d-4b25-8e8b-807b44067441_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/55b2366529c6.jpg',
  },
  'the-word-before-words-day-5': {
    substackUrl: 'https://wokegod.substack.com/p/the-word-before-words-day-45',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/480531a6-a2df-4031-ab2e-17a64ea57933_1456x816.jpeg',
    substackImageLocal: '/images/substack-cache/3b5dcb2e36e3.jpg',
  },
  'the-work-of-god-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/the-work-of-god-day-16-week-88',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/6d4e918f-3250-4da6-b1b2-6d88de03f98a_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/748b6cfac650.jpg',
  },
  'the-work-of-god-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/the-work-of-god-day-26-week-88',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/49f7bf05-f838-4164-bd98-64b9eebebf34_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/39284eeb19ba.jpg',
  },
  'the-work-of-god-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/the-work-of-god-day-36-week-88',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/7ecbeb3a-87a9-4bc7-bdf2-7f9c6a623c00_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/b7725b39dce6.jpg',
  },
  'the-work-of-god-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/the-work-of-god-day-46-week-88',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/b49a8209-c274-4b92-970c-c75b837e519a_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/7c319fd0f722.jpg',
  },
  'the-work-of-god-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/the-work-of-god-day-56-week-88',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/d0d36ecb-2184-49cf-9d5b-e82a073c41d2_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/b6706c708ee7.jpg',
  },
  'the-work-of-god-day-6': {
    substackUrl:
      'https://wokegod.substack.com/p/the-work-of-god-day-66-week-88',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/9bb9a736-4f60-46fa-acfc-7ca7f257ae73_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/356dee0b62a5.jpg',
  },
  'too-busy-for-god-day-1': {
    substackUrl: 'https://wokegod.substack.com/p/too-busy-for-god',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/dd8251b1-ffc0-4b70-bbc0-1cdfabb1874f_1536x1024.png',
    substackImageLocal: '/images/substack-cache/33cd9f952103.png',
  },
  'too-busy-for-god-day-2': {
    substackUrl: 'https://wokegod.substack.com/p/too-busy-for-god-16',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/b98fdf66-1264-4ece-8da7-ad9553c20fd9_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/d0ed47ec58f7.jpg',
  },
  'too-busy-for-god-day-3': {
    substackUrl: 'https://wokegod.substack.com/p/too-busy-for-god-26',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/ac681c9a-d45c-4ab6-b2bd-c8341771ddda_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/10629e7cd0b9.jpg',
  },
  'too-busy-for-god-day-4': {
    substackUrl: 'https://wokegod.substack.com/p/too-busy-for-god-36',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/4241e747-21b7-4739-ae07-dd943d39592a_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/43939a27672e.jpg',
  },
  'too-busy-for-god-day-5': {
    substackUrl: 'https://wokegod.substack.com/p/too-busy-for-god-46',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/72afd803-48ae-47b1-84ae-8f9ba6a23aa3_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/acfe8e4fc86d.jpg',
  },
  'too-busy-for-god-day-6': {
    substackUrl: 'https://wokegod.substack.com/p/too-busy-for-god-56',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/8fbbadfc-5856-4322-8905-d50980da8b00_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/2ae799aec24a.jpg',
  },
  'what-does-it-mean-to-believe-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/what-does-it-mean-to-believe-day',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/b135f1d5-2b05-4082-afd1-ebcb65fd14fd_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/a85b73b6bcb3.jpg',
  },
  'what-does-it-mean-to-believe-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/what-does-it-mean-to-believe-day-221',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/1527cae0-24aa-4d00-bda2-917cda86ebb8_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/f287412f702e.jpg',
  },
  'what-does-it-mean-to-believe-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/what-does-it-mean-to-believe-day-5d9',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/60aacf11-41e2-489d-91ca-c8c22a21948f_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/18a2b50d4c60.jpg',
  },
  'what-does-it-mean-to-believe-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/what-does-it-mean-to-believe-day-546',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/5f206c79-6472-40c9-8783-4b0c76eaf5d9_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/33e306972d90.jpg',
  },
  'what-does-it-mean-to-believe-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/what-does-it-mean-to-believe-day-400',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/453f387b-00d0-4853-a00b-cc5371cda505_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/5357d16b9f72.jpg',
  },
  'what-does-it-mean-to-believe-day-6': {
    substackUrl:
      'https://wokegod.substack.com/p/what-does-it-mean-to-believe-day-78f',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/e7eaa2b5-80d5-40d6-b54c-6a8b4785e6c3_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/391be2db180a.jpg',
  },
  'what-happens-when-you-repeatedly-sin-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/what-happens-when-you-repeatedly',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/d3f2b954-f844-415a-812c-4b4901d1a05c_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/9037fbb52250.jpg',
  },
  'what-happens-when-you-repeatedly-sin-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/what-happens-when-you-repeatedly-b38',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/5d10a30f-ba15-4101-8bbf-0def4d9efc7a_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/5e026b304568.jpg',
  },
  'what-happens-when-you-repeatedly-sin-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/what-happens-when-you-repeatedly-d87',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/a369e2f1-a975-4e8a-8e69-32ec8fffa9ad_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/90759a875b0e.jpg',
  },
  'what-happens-when-you-repeatedly-sin-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/what-happens-when-you-repeatedly-02c',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/fd6368cf-d09c-4351-8846-23087f5b5e62_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/a7e25ce78d23.jpg',
  },
  'what-happens-when-you-repeatedly-sin-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/what-happens-when-you-repeatedly-085',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/f1323b26-1064-4c11-a1ed-7d7a868aa5f0_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/5edc580f134f.jpg',
  },
  'what-happens-when-you-repeatedly-sin-day-6': {
    substackUrl:
      'https://wokegod.substack.com/p/what-happens-when-you-repeatedly-a90',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/a4daca96-a18e-403f-9252-089466f65ed9_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/49edb378430a.jpg',
  },
  'what-is-carrying-a-cross-day-1': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-carrying-a-cross-day-16-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/b39e16a7-b98d-4a22-8afd-9f6eaa6b13e0_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/6a7228e8a57e.jpg',
  },
  'what-is-carrying-a-cross-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-carrying-a-cross-day-26-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/d5ee3bc3-083d-482f-99a3-e32fd8fcc170_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/b0e5ad8ddaa5.jpg',
  },
  'what-is-carrying-a-cross-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-carrying-a-cross-day-36-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/2d7fcfa9-b4a7-47d9-8347-08c312974ef9_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/b7d8db41b4ff.jpg',
  },
  'what-is-carrying-a-cross-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-carrying-a-cross-day-46-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/7cb54829-6393-420c-ad50-64b2d4da1d87_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/ab9579c3d774.jpg',
  },
  'what-is-carrying-a-cross-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-carrying-a-cross-day-56-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/cc1d91a6-81ad-45c5-a7aa-5e532789d0ad_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/9cb91f09dfc7.jpg',
  },
  'what-is-carrying-a-cross-day-6': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-carrying-a-cross-day-66-week',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/3bb8091a-8f1b-4857-9d6c-797e7d109c2f_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/ec120184a379.jpg',
  },
  'what-is-the-gospel-day-1': {
    substackUrl: 'https://wokegod.substack.com/p/what-is-the-gospel-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/ef2292f5-a172-44cb-891f-d326a151b329_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/f03aa9a35cc9.jpg',
  },
  'what-is-the-gospel-day-2': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-the-gospel-day-26-week-28',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/09cd9751-9dbb-4df5-a5ee-43c06b15d38c_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/c05d1b1a1294.jpg',
  },
  'what-is-the-gospel-day-3': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-the-gospel-day-36-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/cf6afdb2-0317-4ecb-93ff-4a65f81e650d_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/c132269b69b8.jpg',
  },
  'what-is-the-gospel-day-4': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-the-gospel-day-46-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/9344d783-1b62-4734-9791-67462128bb4b_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/f221a7ff1a98.jpg',
  },
  'what-is-the-gospel-day-5': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-the-gospel-day-56-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/f48260fb-e627-4e04-8126-27f60ccaafab_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/0e3083948df4.jpg',
  },
  'what-is-the-gospel-day-6': {
    substackUrl:
      'https://wokegod.substack.com/p/what-is-the-gospel-day-66-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/39f947a0-71e6-42e9-bbca-59d0ef1ff016_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/430701b5e0e6.jpg',
  },
  'why-jesus-day-1': {
    substackUrl: 'https://wokegod.substack.com/p/why-jesus-day-16-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/ebcb3bac-4822-4510-b9f3-1c8b9db3d2ae_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/d141779ce5bd.jpg',
  },
  'why-jesus-day-2': {
    substackUrl: 'https://wokegod.substack.com/p/why-jesus-day-26-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/22c29df9-0bc9-4425-8222-b5322ff91f51_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/bd9bc88570e2.jpg',
  },
  'why-jesus-day-3': {
    substackUrl: 'https://wokegod.substack.com/p/why-jesus-day-36-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/9ddd0068-6c55-4ac2-8232-cc76db2f440f_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/6d64bf1e3a03.jpg',
  },
  'why-jesus-day-4': {
    substackUrl: 'https://wokegod.substack.com/p/why-jesus-day-46-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/1601ca56-c775-47b5-b855-5c8081fcce75_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/72f0621c6c43.jpg',
  },
  'why-jesus-day-5': {
    substackUrl: 'https://wokegod.substack.com/p/why-jesus-day-56-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/a61c64eb-adfd-43b1-9f97-5866108b607f_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/2761ee8f74ac.jpg',
  },
  'why-jesus-day-6': {
    substackUrl: 'https://wokegod.substack.com/p/why-jesus-day-66-week-18',
    substackImage:
      'https://substack-post-media.s3.amazonaws.com/public/images/5428551f-fc1b-4ad6-8cc2-cd32a2be2b08_1530x857.jpeg',
    substackImageLocal: '/images/substack-cache/15bad213428e.jpg',
  },
}
