/**
 * The Voices bank — real, attributed quotes from the reference corpus.
 *
 * voices-bank.json is generated by scripts/edition/build-voices-bank.mjs,
 * which verifies every attribution against the actual local source files
 * (several commentary files are mislabeled Gutenberg bundles; the script
 * attributes by each file's true in-file title and asserts every quote is
 * a verbatim substring of its verified source). Regenerate with:
 *
 *   node scripts/edition/build-voices-bank.mjs
 *
 * The bank is imported as a module so it bundles for the Workers runtime —
 * never read from the filesystem at request time. Selection is UTC
 * days-since-epoch arithmetic: every reader opening the page on the same
 * UTC day hears the same voice, and no voice repeats inside a 30-day
 * window (the bank is far larger than 30).
 */
import bank from './voices-bank.json'

export interface VoiceEntry {
  /** Verbatim words, whitespace-normalized only. */
  quote: string
  /** The real person who wrote them. */
  author: string
  /** The verified work the words come from. */
  work: string
}

export const VOICES: VoiceEntry[] = bank.entries

const MS_PER_UTC_DAY = 86_400_000

/**
 * Deterministically pick the voice for the UTC day containing `date`.
 * Same UTC day in, same entry out — never random, never time-of-day
 * dependent. Throws on an empty bank rather than inventing a fallback.
 */
export function pickVoiceForDay(
  date: Date,
  options: { recent?: { quote: string; author: string; daysAgo: number }[] } = {},
): VoiceEntry {
  if (VOICES.length === 0) {
    throw new Error(
      'voices-bank.json has no entries — regenerate it with scripts/edition/build-voices-bank.mjs',
    )
  }
  const daysSinceEpoch = Math.floor(
    Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()) /
      MS_PER_UTC_DAY,
  )
  const index =
    ((daysSinceEpoch % VOICES.length) + VOICES.length) % VOICES.length
  if (!options.recent) return VOICES[index]

  // Daily Bread V2 (plan §42): walk forward from the day's voice past any
  // quote printed in the last 30 days and, where the bank allows, any author
  // printed in the last week (a soft penalty: the bank has 15 authors).
  const quotes = new Set(options.recent.filter((r) => r.daysAgo <= 30).map((r) => r.quote))
  const authors = new Set(options.recent.filter((r) => r.daysAgo <= 7).map((r) => r.author))
  const walk = (ok: (v: VoiceEntry) => boolean) => {
    for (let step = 0; step < VOICES.length; step += 1) {
      const v = VOICES[(index + step) % VOICES.length]
      if (!quotes.has(v.quote) && ok(v)) return v
    }
    return null
  }
  return walk((v) => !authors.has(v.author)) ?? walk(() => true) ?? VOICES[index]
}
